
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return Promise.all([
    knex('cities').del(),
    knex.raw('ALTER SEQUENCE cities_id_seq RESTART WITH 1'),
    knex('cities').then(function() {
      // Inserts seed entries
      return knex('cities').insert([
        {
          name: "Madrid",
          description: "Madrid, the capital of Spain, is a cosmopolitan city with a large cultural and artistic heritage. Besides being a cultural destination, Madrid is also a lively city with many pubs, cafes, and nightclubs. In Madrid, there are many museums such as the Nacional Del Prado, Museum of Americas and the Railway Museum that are definitely worth visiting. Madrid also has several quite unique and interesting tourist spots that you could explore. For example, the open-air pool with several giant slides that the kids just love. There is also El Rastro, an authentic Spanish flea market where you can find absolutely everything.",
          coordinate_latitude: 40.4168,
          coordinate_longitude: -3.7038,
          zoom: 5.8,
          avg_daily_expense: 60,
          city_image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
          country: "SPAIN",
          zone_id: 1,
        },
        {
          name: "Valencia",
          description: "Valencia has many of the things that attracts tourists to Spain, all in one place: The city has a vibrant old centre, with a knot of little streets and splendid medieval buildings like the UNESCO-listed Lonja de la Seda. Valencia is also right on the Mediterranean, so you can laze on broad sandy beaches and tuck into delectable cuisine that draws on the sea. This is the home of paella, surely the most famous Spanish dish of all. There are also ultra-modern visitor attractions at the City of the Arts and Sciences, and it all goes to make Valencua one of Spain’s most complete destinations.",
          coordinate_latitude: 39.4699,
          coordinate_longitude: -0.3763,
          zoom: 5.8,
          avg_daily_expense: 53,
          city_image: "https://blog.eurail.com/wp-content/uploads/2016/07/View-on-Peniscola-from-the-top-of-Pope-Lunas-Castle-Valencia-Spain.jpg",
          country: "SPAIN",
          zone_id: 1,
        },
        {
          name: "Bilbao",
          description: "Staggering architecture, a venerable dining scene and stunning landscapes just outside the city centre: Bilbao is one of the great treasures of the Basque Country. travellers generally come to Bilbao to see the Guggenheim—some for the art inside, but many for the amazing building itself. The Fine Arts Museum and the Basque Museum may not have been designed by Frank Gehry, but are worth a visit, and you can catch international opera stars at the Palacio Euskalduna.",
          coordinate_latitude: 43.2630,
          coordinate_longitude: -2.9350,
          zoom: 5.8,
          avg_daily_expense: 48,
          city_image: "https://images.unsplash.com/photo-1566993850427-6324a91bbd32?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1967&q=80",
          country: "SPAIN",
          zone_id: 1,
        },
        {
          name: "Zaragoza",
          description: "The ethereal image of the multi-domed Basílica del Pilar reflected in the Río Ebro is a potent symbol of Zaragoza, one of Spain’s most underrated regional capitals. There's plenty more fine architecture here too, including a turreted castle with an interior like a mini-Alhambra, and some very creatively displayed underground Roman remains, but Zaragoza's appeal goes well beyond its monuments. Spain’s fifth-largest city (and home to more than half of Aragón's 1.3 million residents), it has one the best tapas and bar scenes in the country and is well stocked with the epoch-defining art of local lad Francisco de Goya.",
          coordinate_latitude: 41.6488,
          coordinate_longitude: -0.8891,
          zoom: 5.8,
          avg_daily_expense: 49,
          city_image: "https://img.theculturetrip.com/1440x807/smart/wp-content/uploads/2018/03/zaragoza-spain-.jpg",
          country: "SPAIN",
          zone_id: 1,
        },
        {
          name: "Barcelona",
          description: "Well-known for its impressive architecture, laid-back lifestyle, and cosmopolitan character, Barcelona should be included in every travellers list of cities to visit. Take a walk down the magnificent La Rambla Street, stroll around the wonderful Gothic Quarter, visit la sagrada familia as well as la pedrera, fantastic architecture from Goy. Finally, make sure check out the Montserrat Mountainn and also climb up the mountain to get to the bunkers where you will have the best spots to chill and enjoy a panoramic view of the city as a whole.",
          coordinate_latitude: 41.3851,
          coordinate_longitude: 2.1734,
          zoom: 5.8,
          avg_daily_expense: 67,
          city_image: "https://images.unsplash.com/photo-1562191184-704e6744136d?ixlib=rb-1.2.1&auto=format&fit=crop&w=2089&q=80",
          country: "SPAIN",
          zone_id: 1,
        },
        {
          name: "Toulouse",
          description: "Toulouse, or La Ville Rose as it’s also known, is distinctly southern European with its dusty-red buildings that sit under pastel blue skies. This ‘pink city’ may be in the south of France but it’s just 75 miles from the Spanish border and has strong roots in Occitania, a historical linguistic region that encompassed this part of France and small areas of Italy and Catalunya. No wonder then that a night out in Toulouse has a Spanish twist. Tapas bars abound, with menus mixing Basque pintxos with local produce. 5he cultural cassoulet and layering youthful energy over a laid-back southern soul makes it a perfect destination.",
          coordinate_latitude: 43.6047,
          coordinate_longitude: 1.4442,
          zoom: 5.8,
          avg_daily_expense: 56,
          city_image: "https://static.standard.co.uk/s3fs-public/thumbnails/image/2019/04/26/09/toulouse-shutterstock.jpg?width=1000&height=614&fit=bounds&format=pjpg&auto=webp&quality=70&crop=16:9,offset-y0.5",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Marseille",
          description: "Grit and grandeur coexist seamlessly in Marseille, an exuberantly multicultural port city with a pedigree stretching back to classical Greece and a fair claim to the mantle of France's second city. Once seen as somewhat dirty and dangerous, and lacking the glamour of Cannes or St-Tropez, this black sheep of the Provençal coastline has blossomed in cultural confidence since its 2013 stint as the European Capital of Culture. The addition of a brace of swanky new museums is just the outward sign of an optimism and self-belief that's almost palpable.",
          coordinate_latitude: 43.2965,
          coordinate_longitude: 5.3698,
          zoom: 5.8,
          avg_daily_expense: 53,
          city_image: "https://i.imgur.com/llMlpnZ.jpg",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Nice",
          description: "Nice’s unofficial anthem is Nissa La Bella, and you can’t help but agree with this sentiment when you visit the French Riviera’s largest city. Nice’s beauty comes from the 19th-century mansions on its promenades and boulevards, from the city’s Italianate old quarter and the rugged natural terrain that provides countless wondrous vantage points. Artists have always cherished this scenery, rendered even more beautiful by the unique light. So Nice is now also one of the best places to go in Europe for art galleries, with museums dedicated to Chagall and Matisse. Add great cuisine, a perfect climate and more than a dash of Riviera glamour, you’ve got a very special place.",
          coordinate_latitude: 43.7102,
          coordinate_longitude: 7.2620,
          zoom: 5.8,
          avg_daily_expense: 52,
          city_image: "https://www.thetrainline.com/cmsmedia/cms/8266/nice_x2.jpg",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Lyon",
          description: "At the crossroads of central Europe and the Atlantic, the Rhineland and the Mediterranean, grand old Lyon is France's third-largest metropolis and its gastronomic capital. Savouring timeless traditional dishes in checked-tableclothed bouchons (small bistros) creates unforgettable memories – as do the majestic Roman amphitheatres of Fourvière, the cobbled Unesco-listed streets of Vieux Lyon, and the audacious modern architecture of the new Confluence neighbourhood.",
          coordinate_latitude: 45.7640,
          coordinate_longitude: 4.8357,
          zoom: 5.8,
          avg_daily_expense: 55,
          city_image: "https://images.unsplash.com/photo-1537015125382-74e1f1c99ac4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Turin",
          description: "Turin is the capital city of Piedmont in northern Italy, known for its refined architecture and cuisine. The Alps rise to the northwest of the city. Stately baroque buildings and old cafes line Turin's boulevards and grand squares such as Piazza Castello and Piazza San Carlo. Nearby is the soaring spire of the Mole Antonelliana, a 19th-century tower housing the interactive National Cinema Museum. There's a whiff of Paris in Turin's elegant tree-lined boulevards and echoes of Vienna in its stately art-nouveau cafes, but make no mistake – this elegant, Alp-fringed city is utterly self-possessed.",
          coordinate_latitude: 45.0703,
          coordinate_longitude: 7.6869,
          zoom: 5.8,
          avg_daily_expense: 66,
          city_image: "https://dpv87w1mllzh1.cloudfront.net/alitalia_discover/attachments/data/000/000/476/original/torino-royal-torino-1920x1080.jpg?1519196650",
          country: "ITALY",
          zone_id: 1,
        },
        {
          name: "Milan",
          description: "Milan, a metropolis in Italy's northern Lombardy region, is a global capital of fashion and design. Home to the national stock exchange, it’s a financial hub also known for its high-end restaurants and shops. The Gothic Duomo di Milano cathedral and the Santa Maria delle Grazie convent, housing Leonardo da Vinci’s mural “The Last Supper,” testify to centuries of art and culture. Milan is Italy’s city of the future, a fast-paced metropolis where money talks, creativity is big business and looking good is an art form.",
          coordinate_latitude: 45.4642,
          coordinate_longitude: 9.1900,
          zoom: 5.8,
          avg_daily_expense: 62,
          city_image: "https://images.unsplash.com/photo-1512397739299-fe5a4327d192?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
          country: "ITALY",
          zone_id: 1,
        },
        {
          name: "Geneva",
          description: "Geneva is a city in Switzerland that lies at the southern tip of expansive Lac Léman (Lake Geneva). Surrounded by the Alps and Jura mountains, the city has views of dramatic Mont Blanc. Headquarters of Europe’s United Nations and the Red Cross, it’s a global hub for diplomacy and banking. French influence is widespread, from the language to gastronomy and bohemian districts like Carouge. Like the swans that frolic on its eponymous Alpine lake (Europe's largest), Geneva (Genève) is a rare bird. Constantly perceived as the Swiss capital (it isn't), Switzerland's second-largest city is slick and cosmopolitan.",
          coordinate_latitude: 46.2044,
          coordinate_longitude: 6.1432,
          zoom: 5.8,
          avg_daily_expense: 74,
          city_image: "http://www.swissgearlife.com/wp-content/uploads/2019/06/welcome-to-geneva-switzerland.jpg",
          country: "SWITZERLAND",
          zone_id: 1,
        },
        {
          name: "Zurich",
          description: "Culturally vibrant, efficiently run and attractively set at the meeting of river and lake, Zürich is regularly recognised as one of the world's most liveable cities. Long known as a savvy, hard-working financial centre, Switzerland's largest and wealthiest metropolis has also emerged in the 21st century as one of Central Europe's hippest destinations, with an artsy, post-industrial edge that is epitomised in its exuberant summer Street Parade.",
          coordinate_latitude: 47.3769,
          coordinate_longitude: 8.5417,
          zoom: 5.8,
          avg_daily_expense: 72,
          city_image: "https://images.unsplash.com/photo-1554229296-ad6d6ddc2db7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
          country: "SWITZERLAND",
          zone_id: 1,
        },
        {
          name: "Strasbourg",
          description: "Strasbourg is the capital city of the Grand Est region, formerly Alsace, in northeastern France. Strasbourg is the perfect overture to all that is idiosyncratic about Alsace – walking a fine tightrope between France and Germany and between a medieval past and a progressive future. Its Gothic Cathédrale Notre-Dame features daily shows from its astronomical clock and sweeping views of the Rhine River from partway up its 142m spire",
          coordinate_latitude: 48.5734,
          coordinate_longitude: 7.7521,
          zoom: 5.8,
          avg_daily_expense: 55,
          city_image: "https://images.unsplash.com/photo-1552326859-b25d03868ead?ixlib=rb-1.2.1&auto=format&fit=crop&w=2032&q=80",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Paris",
          description: "Paris. Just the name conjures images of fresh baguettes, tree-lined streets, artists, glamour, sophistication, and men in jaunty berets. The French capital has captured the hearts and imagination of people the world over and continues to remain one of the world’s most visited cities to this day. What to see in Paris… Where to start?! The Eiffel Tour is probably the best place. Go and marvel at it during the day then come back at night and watch it twinkle on the hour, every hour.",
          coordinate_latitude: 48.8566,
          coordinate_longitude: 2.3522,
          zoom: 5.8,
          avg_daily_expense: 79,
          city_image: "https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateParis_Heroshutterstock_112137761.jpg",
          country: "FRANCE",
          zone_id: 1,
        },
        {
          name: "Brussels",
          description: "Welcome to Brussels, the city where French Fries and Chocolate Pralines were invented. Did you know that almost every beer produced in Brussels has its own glass and needs to be served in it? The main airport in the city sells a crazy amount of chocolate and an average citizen of Brussels drinks more than 130 liters of beer per a year. Top sightseeing spots in the city include The Atomium and La Grande Place with magnificient buildings.",
          coordinate_latitude: 50.8503,
          coordinate_longitude: 4.3517,
          zoom: 5.8,
          avg_daily_expense: 61,
          city_image: "https://images.unsplash.com/photo-1526164756841-ec188df0730e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2978&q=80",
          country: "BELGIUM",
          zone_id: 1,
        },
        {
          name: "Antwerp",
          description: "Antwerp (Antwerpen/Anvers in Dutch/French) is Belgium’s second city, biggest port and capital of cool. It has long been a powerful magnet for everyone from fashion moguls and club queens to art lovers and diamond dealers. Antwerp retains an intriguing medieval heart with plenty of café-filled cobbled lanes, a riverside fortress and a truly impressive cathedral. Today, however, Antwerp’s top drawcards are its vibrant fashion and entertainment scene.",
          coordinate_latitude: 51.2194,
          coordinate_longitude: 4.4025,
          zoom: 5.8,
          avg_daily_expense: 62,
          city_image: "https://images.unsplash.com/photo-1551522812-b9a174a623c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1652&q=80",
          country: "BELGIUM",
          zone_id: 1,
        },
        {
          name: "Amsterdam",
          description: "Golden Age canals lined by tilting gabled buildings are the backdrop for Amsterdam's treasure-packed museums, vintage-filled shops and hyper-creative drinking, dining and design scenes. Amsterdam is the Netherlands’ capital, known for its artistic heritage, elaborate canal system and narrow houses with gabled facades, legacies of the city’s 17th-century Golden Age. Its Museum District houses the Van Gogh Museum, works by Rembrandt and Vermeer at the Rijksmuseum, and modern art at the Stedelijk.",
          coordinate_latitude: 52.3667,
          coordinate_longitude: 4.8945,
          zoom: 5.8,
          avg_daily_expense: 74,
          city_image: "https://images.unsplash.com/photo-1468436385273-8abca6dfd8d3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1594&q=80",
          country: "NETHERLANDS",
          zone_id: 1,
        },
        {
          name: "Frankfurt",
          description: "In this enchanting corner of Germany, the finer things in life take pride of place: good food, great wine, glorious walking and cycling, and exceptional art everywhere, from magnificent museums to quirky street sculptures. The city is a business hotspot and most people that travel to Frankfurt are there for business. This is not surprising regarding the fact that Frankfurt is the European banking capital. That said the city definitely has a cosmopolitan vibe.",
          coordinate_latitude: 50.1109,
          coordinate_longitude: 8.6821,
          zoom: 5.8,
          avg_daily_expense: 58,
          city_image: "https://images.unsplash.com/photo-1540646794357-6cbbd6f3501e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1568&q=80",
          country: "GERMANY",
          zone_id: 1,
        },
        {
          name: "Cologne",
          description: "Cologne (Köln) offers a mother lode of attractions, led by its famous cathedral whose filigree twin spires dominate the skyline. The city’s museum landscape is especially strong when it comes to art but also has something in store for fans of chocolate, sports and even Roman history. Cologne's people are known for their liberalism and joie de vivre; it’s easy to have a good time with them in the beer halls of the Altstadt or during Carnival.",
          coordinate_latitude: 50.9375,
          coordinate_longitude: 6.9603,
          zoom: 5.8,
          avg_daily_expense: 62,
          city_image: "https://images.unsplash.com/photo-1561624485-0e43bcc1836d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
          country: "GERMANY",
          zone_id: 1,
        },
      ]);
    }),
  ]);
};
