
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return Promise.all([
    knex('activities').del(),
    knex.raw('ALTER SEQUENCE activities_id_seq RESTART WITH 1'),
    knex('activities').then(function() {
      // Inserts seed entries
      return knex('activities').insert([
        {
          name: "Museo del prado",
          description: "More than 7000 paintings are held in the Museo del Prado’s collection, acting like a window onto the historical vagaries of the Spanish soul",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/fed1a2b677245627be71a1a62f48fbbc-museo-del-prado.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Parque del Buen Retiro",
          description: "The gardens of El Retiro are as beautiful as any you’ll find in a European city. Littered with marble monuments, landscaped lawns and occasional elegant buildings.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/85295461ad2f47599cc4f8cdf1e2b4d7-parque-del-buen-retiro.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Plaza Mayor",
          description: "Madrid's grand central square, a rare but expansive opening in the tightly packed streets of central Madrid, is one of the prettiest open spaces in Spain",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/f8de446b393d42220616d7df68ea4120-plaza-mayor.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Centro de Arte Reina Sofía",
          description: "Home to Picasso’s Guernica, arguably Spain’s most famous artwork, the Centro de Arte Reina Sofía is Madrid’s premier collection of contemporary art. Other major drawcards are works by Salvador Dalí and Joan Miró",
          activity_image: "https://lonelyplanetimages.imgix.net/mastheads/shutterstock_155320763.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Palacio Real",
          description: "Spain's lavish Palacio Real is a jewel box of a palace, although it's used only occasionally for royal ceremonies; the royal family moved to the modest Palacio de la Zarzuela years ago.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/1dbadc1f025e287e06fe6a4e50a6379e-palacio-real.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Plaza de Toros",
          description: "East of central Madrid, the Plaza de Toros Monumental de Las Ventas (Las Ventas) is the most important and prestigious bullring in the world.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/78fa4cb3fc0741bfcb16d6941d2622e3-plaza-de-toros.jpg?fit=crop&w=1920&h=832",
          city_id: 1,
        },
        {
          name: "Ciudad de las Artes y las Ciencias",
          description: "This aesthetically stunning complex occupies a massive 350,000-sq-metre swath of the old Turia riverbed. It’s occupied by a series of spectacular buildings.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/8d4ea9f9dcd8b11314033398d32f950c-ciudad-de-las-artes-y-las-ciencias.jpg?fit=crop&w=1920&h=832",
          city_id: 2,
        },
        {
          name: "Catedral de Valencia",
          description: "Valencia’s cathedral was built over a mosque after the 1238 reconquest. Its low, wide, brick-vaulted triple nave is mostly Gothic, with neoclassical side chapels.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/38d679da67db0c9db67e03b8e7f8103f-lpl-02702.jpg?fit=crop&w=1920&h=832",
          city_id: 2,
        },
        {
          name: "Museo Nacional de Cerámica",
          description: "Inside a striking palace, this ceramics museum celebrates an important local industry. There you can learn about the history of ceramics from baroque to modern",
          activity_image: "https://cloud10.todocoleccion.online/postales-comunidad-valenciana/tc/2014/10/15/19/45728091.jpg",
          city_id: 2,
        },
        {
          name: "La Lonja",
          description: "This splendid building, a Unesco World Heritage Site, was originally Valencia’s silk and commodity exchange, built in the late 15th century when the city was booming.",
          activity_image: "https://www.timetravelturtle.com/wp-content/uploads/2018/08/Valencia-2018-3_new.jpg",
          city_id: 2,
        },
        {
          name: "Museo de Bellas Artes",
          description: "right and spacious, this gallery ranks among Spain’s best. Highlights include a collection of magnificent late-medieval altarpieces, and works by several Spanish masters, including Goya",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/3977a54556b6fd76206fc0d3b5d9c23b-museo-de-bellas-artes.jpg?fit=crop&w=1920&h=832",
          city_id: 2,
        },
        {
          name: "Mercado Central",
          description: "Valencia’s vast Modernista covered market, constructed in 1928, is a swirl of smells, movement and colour with spectacular seafood counters",
          activity_image: "https://lonelyplanetimages.imgix.net/assets/image/7a6dd13e83de9f912c49d76285ba0b4eba30c7a6e5521daf2a3faaede6ca176e/4a4482681c5b2cd4e12dedab377d7cec1d18592be95f96003be07a003a57235d.jpg?fit=crop&w=1920&h=832",
          city_id: 2,
        },
        {
          name: "Museo Guggenheim Bilbao",
          description: "It sparked the city’s inspired regeneration, stimulated further development and placed Bilbao firmly in the international art and tourism spotlight.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/222db16fcfa1b7dd0fb07c836cb8e6bf-museo-guggenheim.jpg?fit=crop&w=1920&h=832",
          city_id: 3,
        },
        {
          name: "Casco Viejo",
          description: "The compact Casco Viejo, Bilbao’s atmospheric old quarter, is full of charming streets, boisterous bars and plenty of quirky and independent shops.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/11fa93f10e9c9152579efbac79947fa7-casco-viejo.jpg?fit=crop&w=1920&h=832",
          city_id: 3,
        },
        {
          name: "Museo de Bellas Artes",
          description: "The Museo de Bellas Artes houses a compelling collection that includes everything from Gothic sculptures to 20th-century pop art.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/b9f6fc156124f82579f8bcb891aa4fa6-museo-de-bellas-artes.jpg?fit=crop&w=1920&h=832",
          city_id: 3,
        },
        {
          name: "Azkuna Zentroa",
          description: "Take a neglected wine storage warehouse, convert it into a leisure and cultural centre, add a bit of Bilbao style and the result is the Azkuna Zentroa (Alhóndiga)",
          activity_image: "https://cms.guggenheim-bilbao.eus/uploads/2019/08/azkuna-zentroa-bilbao.jpg",
          city_id: 3,
        },
        {
          name: "Museo Marítimo Ría de Bilbao",
          description: "This interactive maritime museum, appropriately situated down on the waterfront, uses bright and well-designed displays to bring the watery depths of Bilbao and Basque maritime history to life",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/64f236232ce3d168b578ae1002c7ab5d-museo-maritimo-ria-de-bilbao.jpg?fit=crop&w=1920&h=832",
          city_id: 3,
        },
        {
          name: "Funicular de Artxanda",
          description: "For a breathtaking view over the city and the wild Basque mountains beyond, take a trip on the funicular railway way up the steep slope to the summit of Artxanda.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/cb8db5622fedcfdbc61faa2964700cd0-funicular-de-artxanda.jpg?fit=crop&w=1920&h=832",
          city_id: 3,
        },
        {
          name: "Aljafería Palace",
          description: "The Aljafería is Spain's finest Islamic-era edifice outside Andalucía. Built as a fortified palace for Zaragoza's Islamic rulers in the 11th century.",
          activity_image: "https://img.theculturetrip.com/x/smart/wp-content/uploads/2016/12/aljaferia.jpg",
          city_id: 4,
        },
        {
          name: "Museo Goya – Colección Ibercaja",
          description: "Apart from Madrid’s Museo del Prado, this exceedingly well-laid-out museum contains arguably the best exposé of the work of one of Spain’s most revered artists.",
          activity_image: "https://museogoya.ibercaja.es/img/obras/casa-jeronimo-cosida.jpg",
          city_id: 4,
        },
        {
          name: "La Seo Catedral",
          description: "Dominating the eastern end of Plaza del Pilar, La Seo is Zaragoza's finest work of Christian architecture, built between the 12th and 17th centuries and displaying a fabulous spread of styles from Romanesque to baroque",
          activity_image: "https://lonelyplanetimages.imgix.net/mastheads/GettyImages-144106520_master.jpg?fit=crop&w=1920&h=832",
          city_id: 4,
        },
        {
          name: "Basílica de Nuestra Señora del Pilar",
          description: "A striking Baroque Basilica, it is here that many believe that Santiago – one of Jesus’ disciples and referred to as James in the Bible – saw the Virgin Mary ascend a marble pillar.",
          activity_image: "https://www.tegustaviajar.com/wp-content/uploads/2019/02/basilica-del-pilar.jpg",
          city_id: 4,
        },
        {
          name: "Museo del Teatro de Caesaraugusta",
          description: "The remains of an ancient Roman theater that once used to seat 6,000 people, this impressive monument was excavated in 1972. From the ground floor one can enjoy panoramic views of the excavation process",
          activity_image: "https://cdn1.soydezaragoza.es/wp-content/uploads/2017/06/fachada-Teatro-Romano-de-Zaragoza.jpg",
          city_id: 4,
        },
        {
          name: "Museo Origami",
          description: "This museum devoted to the art of folding paper has six galleries of permanent and temporary exhibitions of a staggeringly high standard.",
          activity_image: "https://m.eldiario.es/fotos/museo-unico-mundo_EDIIMA20180824_0236_19.jpg",
          city_id: 4,
        },
        {
          name: "La Sagrada Família",
          description: "If you have time for only one sightseeing outing, this should be it. La Sagrada Família inspires awe by its sheer verticality, and in the manner of the medieval cathedrals it emulates, it’s still under construction",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/8ae1c56041e64517e29372a889f1beb7-la-sagrada-familia.jpg?fit=crop&w=1920&h=832",
          city_id: 5,
        },
        {
          name: "Park Güell",
          description: "North of Gràcia, Unesco-listed Park Güell is where architect Antoni Gaudí turned his hand to landscape gardening. It’s a strange, enchanting place where his passion for natural forms really took flight",
          activity_image: "https://lonelyplanetimages.imgix.net/mastheads/GettyImages-509492253_high.jpg?fit=crop&w=1920&h=832",
          city_id: 5,
        },
        {
          name: "Casa Batlló",
          description: "Another of Antoni Gaudí’s most postcard-friendly creations. You won’t need to have visited Barcelona to recognise the building’s roof, the tiles of which are the scales of a great dragon.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/07/Casa-Batll%C3%B3.jpg",
          city_id: 5,
        },
        {
          name: "La Rambla",
          description: "Barcelona's most famous street is both a tourist magnet and a window into Catalan culture, with cultural centres, theatres and intriguing architecture.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/07/Las-Ramblas.jpg",
          city_id: 5,
        },
        {
          name: "Museu Nacional d’Art de Catalunya",
          description: "It houses a vast collection of mostly Catalan art, spanning the early Middle Ages to the early 20th century. The high point is the collection of extraordinary Romanesque frescoes.",
          activity_image: "https://lonelyplanetimages.imgix.net/mastheads/89360343.jpg?fit=crop&w=1920&h=832",
          city_id: 5,
        },
        {
          name: "La Pedrera",
          description: "This madcap Gaudí masterpiece was built in 1905–10 as a combined apartment and office block. its uneven grey stone facade, which ripples around the corner of Carrer de Provença makes it an awesome place to take unforgetable photos.",
          activity_image: "https://lonelyplanetimages.imgix.net/assets/image/2a98617c996abfcbcc2006f4f64736719bbda2a4b26e0f933f8de3a0a67b62f5/32638e23777c6ba9d468a1c94756403da8347d014b74dacf0e65ad2f8374e2bb.jpg?fit=crop&w=1920&h=832",
          city_id: 5,
        },
        {
          name: "Basilique Saint-Sernin",
          description: "Completed in 1100s, the UNECO-listed Saint-Sernin Basilica may be the largest romanesque church in Europe. There’s also a large number of relics in the crypt, more than in any other church",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Basilique-Saint-Sernin.jpg",
          city_id: 6,
        },
        {
          name: "Place du Capitole",
          description: "Toulouse's magnificent main square is the city's literal and metaphorical heart, where Toulousiens turn out en masse on sunny evenings to sip a coffee or an early aperitif at a pavement cafe.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Place-du-Capitole.jpg",
          city_id: 6,
        },
        {
          name: "Couvent des Jacobins",
          description: "This Jacobin convent is the last word in southern French gothic design. It was finished in the 1300s and is noted for its awesome dimensions, with a double nave and vaults that reach almost 30 metres.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Church-of-the-Jacobins-1.jpg",
          city_id: 6,
        },
        {
          name: "Cité de l’Espace",
          description: "The fantastic space museum on the city's eastern outskirts brings Toulouse's illustrious aeronautical history to life through hands-on exhibits, including a moon-running simulator.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Cit%C3%A9-de-lEspace.jpg",
          city_id: 6,
        },
        {
          name: "Musée des Augustins",
          description: "Located within a former Augustinian monastery, this fine-arts museum spans the Roman era through to the early 20th century. Echoing stairwells and high-vaulted chambers are part of the fun",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Mus%C3%A9e-des-Augustins.jpg",
          city_id: 6,
        },
        {
          name: "Fondation Bemberg",
          description: "This luxurious museum of fine arts and historic design is housed within Toulouse’s most impressive hôtel particulier (private mansion), the Hôtel d'Assézat.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/11/Fondation-Bemberg.jpg",
          city_id: 6,
        },
        {
          name: "Vieux Port",
          description: "Ships have docked for millennia at Marseille’s birthplace, the vibrant Vieux Port. The main commercial docks were transferred to the Joliette area in the 1840s, but the old port remains a thriving harbour for fishing",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/b089c412c647e05341592171b6d34ba8-marseille.jpg?fit=crop&w=1920&h=832",
          city_id: 7,
        },
        {
          name: "Basilique Notre-Dame de la Garde",
          description: "Occupying Marseille’s highest point, La Garde (154m), this opulent 19th-century Romano-Byzantine basilica is Marseille's most-visited icon.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Basilique-Notre-Dame-de-la-Garde.jpg",
          city_id: 7,
        },
        {
          name: "Le Panier",
          description: "'The Basket' is Marseille's oldest quarter – site of the original Greek settlement and nicknamed for its steep streets and buildings. Its close, village-like feel and artsy ambience make it a delight to explore",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Le-Panier.jpg",
          city_id: 7,
        },
        {
          name: "Musée d’Histoire de Marseille",
          description: "This intriguing 15,000-sq-metre museum traces the story of 'France's Oldest City' from prehistory (the paintings of the Cosquer Cave) to the present day, across 12 chronological exhibitions.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Mus%C3%A9e-dHistoire-de-Marseille.jpg",
          city_id: 7,
        },
        {
          name: "Musée des Beaux Arts",
          description: "Set in the lavish, colonnaded Palais de Longchamp, Marseille’s oldest museum owes its existence to an 1801 decree of pre-Napoleonic France's short-lived Consulate, which established 15 museums across the country",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/b19b86ef1e9042c667390f423fc93cad-palais-de-longchamp.jpg?fit=crop&w=1920&h=832",
          city_id: 7,
        },
        {
          name: "MuCEM",
          description: "The icon of modern Marseille, this stunning museum explores the history, culture and civilisation of the Mediterranean region through anthropological exhibits, rotating art exhibitions and film.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/MuCEM.jpg",
          city_id: 7,
        },
        {
          name: "Vieux Nice",
          description: "Getting lost among the dark, narrow, winding alleyways of Nice’s old town is a highlight. The layout has barely changed since the 1700s, and it’s now packed with delis, restaurants, boutiques and bars.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Vieille-Ville-1.jpg",
          city_id: 8,
        },
        {
          name: "Promenade des Anglais",
          description: "The most famous stretch of seafront in Nice – if not France – is this vast paved promenade, which gets its name from the English expat patrons who paid for it in 1822.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/bdf8e8edc110a61812472f67f0b8f318-promenade-des-anglais.jpg?fit=crop&w=1920&h=832",
          city_id: 8,
        },
        {
          name: "Colline du Château",
          description: "For the best views over Nice’s red-tiled rooftops, climb the winding staircases up to this wooded outcrop on the eastern edge of the old town.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/86955b38d5d88e812e8ea7b55cea19be-colline-du-chateau.jpg",
          city_id: 8,
        },
        {
          name: "Cathédrale Orthodoxe Russe St-Nicolas",
          description: "Located in the Vieille Ville, the exterior of this landmark is rather unprepossessing, apart from its patterned dome. A casual visitor to the square in front might not even realise that this is the city’s cathedral.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Nice-Cathedral.jpg",
          city_id: 8,
        },
        {
          name: "Musée Matisse",
          description: "This museum, 2km north of the city centre in the leafy Cimiez quarter, houses a fascinating assortment of works by Matisse, including oil paintings, drawings...",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/0808d328be1bbf5e9d094aa8ea900efe-musee-matisse.jpg?fit=crop&w=1920&h=832",
          city_id: 8,
        },
        {
          name: "Cours Saleya Market",
          description: "Split between its beautiful flower market and rightly famous food market. On Mondays, flowers and food make way for a flea market.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/c54bb8b207c0c3df980c875e702294c7-cours-saleya-markets.jpg?fit=crop&w=1920&h=832",
          city_id: 8,
        },
        {
          name: "Fourvière Basilica",
          description: "Crowning the hill, with stunning city panoramas from its terrace, this superb example of late-19th-century French ecclesiastical architecture is lined with magnificent mosaics.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Fourvi%C3%A8re-Basilica.jpg",
          city_id: 9,
        },
        {
          name: "Cathédrale St-Jean-Baptiste",
          description: "Lyon's partly Romanesque cathedral was built between the late 11th and early 16th centuries. The portals of its Flamboyant Gothic facade are decorated with 280 square stone medallions",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/943d993013feb0e735f98b35bbebfa70-cathedrale-st-jean-baptiste.jpg?fit=crop&w=1920&h=832",
          city_id: 9,
        },
        {
          name: "Musées Gadagne",
          description: "Housed in a 16th-century mansion built for two rich Florentine bankers, this twin-themed exhibition space chronicles the city’s layout as its silk-weaving, cinema and transportation evolved",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/afbe6cee925c835f022c9df7ed8ab347-musees-gadagne.jpg?fit=crop&w=1920&h=832",
          city_id: 9,
        },
        {
          name: "Ancient Theatre of Fourvière",
          description: "Lyon's Roman theatre, built around 15 BC and enlarged in AD 120, sat an audience of 10,000. Romans held poetry readings and musical recitals in the smaller, adjacent odéon.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Ancient-Theatre-of-Fourvi%C3%A8re.jpg",
          city_id: 9,
        },
        {
          name: "Institut Lumière",
          description: "Cinema's glorious beginnings are showcased at the art nouveau home of Antoine Lumière, who moved to Lyon with sons Auguste and Louis in 1870. ",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Institut-Lumi%C3%A8re.jpg",
          city_id: 9,
        },
        {
          name: "Place des Terreaux",
          description: "The centrepiece of the Presqu'île's beautiful central square is a 19th-century fountain made of 21 tonnes of lead and sculpted by Frédéric-Auguste Bartholdi ",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/09725aa1c74318de6506ae99595d4115-place-des-terreaux.jpg?fit=crop&w=1920&h=832",
          city_id: 9,
        },
        {
          name: "Palazzo Reale",
          description: "Statues of the mythical twins Castor and Pollux guard the entrance to this eye-catching palace and also watch over the magical border between the sacred and diabolical city's halves",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/02/Palazzo-Reale.jpg",
          city_id: 10,
        },
        {
          name: "Cathedral of San Giovanni Battista",
          description: "Turin's cathedral was built between 1491 and 1498 on the site of three 14th-century basilicas and, before that, a Roman theatre. It is a highly trafficked church",
          activity_image: "https://media-cdn.tripadvisor.com/media/photo-s/10/f7/84/39/cattedrale-di-san-giovanni.jpg",
          city_id: 10,
        },
        {
          name: "Mole Antonelliana",
          description: "The symbol of Turin, this 167m tower with its distinctive aluminium spire appears on the Italian two-cent coin. It was originally intended as a synagogue when construction began in 1862.",
          activity_image: "https://cdn.marcopolo.tv/960x480/media/post/rd4te88/mole.jpg",
          city_id: 10,
        },
        {
          name: "Basilica di Superga",
          description: "The result of Vittorio Amedeo II's 1706 promise, to build a basilica to honour the Virgin Mary if Turin was saved from besieging French and Spanish armies",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Basilica-di-Superga.jpg",
          city_id: 10,
        },
        {
          name: "Reggia di Venaria Reale",
          description: "OK, it may not enjoy the weighty publicity of its French counterpart, but this is one of the largest royal residences in the world, rescued from ruin by a €235 million 10-year-long restoration project.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/83d401d3aca2e179bd5b77fc7714cbba-reggia-di-venaria-reale.jpg?fit=crop&w=1920&h=832",
          city_id: 10,
        },
        {
          name: "Museo Egizio",
          description: "Opened in 1824 and housed in the austere Palazzo dell'Accademia delle Scienze, this Turin institution houses the most important collection of Egyptian treasures outside Cairo.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/f78615cafacd1b4f6bddf6d54a394af3-museo-egizio.jpg?fit=crop&w=1920&h=832",
          city_id: 10,
        },
        {
          name: "Duomo",
          description: "A vision in pink Candoglia marble, Milan's extravagant Gothic cathedral, 600 years in the making, aptly reflects the city's creativity and ambition.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Milan-Cathedral.jpg",
          city_id: 11,
        },
        {
          name: "Castello Sforzesco",
          description: "Originally a Visconti fortress, this iconic red-brick castle was later home to the mighty Sforza dynasty, who ruled Renaissance Milan. The castle's defences were designed by the multitalented da Vinci",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Castello-Sforzesco.jpg",
          city_id: 11,
        },
        {
          name: "Pinacoteca di Brera",
          description: "Located upstairs from one of Italy’s most prestigious art schools, this gallery houses Milan’s collection of Old Masters, much of it ‘lifted’ from Venice by Napoleon.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Pinacoteca-di-Brera.jpg",
          city_id: 11,
        },
        {
          name: "The Last Supper",
          description: "Milan's most famous mural, Leonardo da Vinci’s The Last Supper, is hidden away on a wall of the refectory adjoining the Basilica di Santa Maria delle Grazie. ",
          activity_image: "https://lonelyplanetimages.imgix.net/assets/image/548b28fda7dcd301301a77b8e5d14f16d57e3bf0c9e7c01e8df1aa80a9a5467c/44d0ea2e00ece56c5f9406e3f0e9c8ea9e9aebba6b08c4456c1390908f81b375.jpg?fit=crop&w=1920&h=832",
          city_id: 11,
        },
        {
          name: "Museo Nazionale Scienza e Tecnologia Leonardo da Vinci",
          description: "Kids and would-be inventors will go goggle-eyed at Milan's science museum, the largest of its kind in Italy. It is a fitting tribute in a city where arch-inventor Leonardo da Vinci did much of his finest work",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Museo-Nazionale-Scienza-e-Tecnologia-Leonardo-da-Vinci.jpg",
          city_id: 11,
        },
        {
          name: "Basilica di Sant'Ambrogio",
          description: "It’s a fitting legacy, built and rebuilt with a purposeful simplicity that is truly uplifting: the seminal Lombard Romanesque basilica.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/03/Sant-Ambrogio.jpg",
          city_id: 11,
        },
        {
          name: "Jet d’Eau",
          description: "When landing by plane, this lakeside fountain is your first dramatic glimpse of Geneva. The 140m-tall structure shoots up water with incredible force – 200km/h, 1360 horsepower.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Jet-dEau.jpg",
          city_id: 12,
        },
        {
          name: "Cathédrale St-Pierre",
          description: "Geneva's cathedral is predominantly Gothic with an 18th-century neoclassical facade. Between 1536 and 1564 Protestant John Calvin preached here; see his seat in the north aisle.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/St-Pierre-Cathedral.jpg",
          city_id: 12,
        },
        {
          name: "Vieille Ville",
          description: "A stroll around Geneva's beautiful Old Town is a must. Its main street, the Grand-Rue, shelters the Maison de Rousseau et de la Literature at No 40, where the 18th-century philosopher Jean-Jacques Rousseau was born.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Vielle-Ville.jpg",
          city_id: 12,
        },
        {
          name: "CERN",
          description: "Founded in 1954, the European Organization for Nuclear Research (CERN), 8km west of Geneva, is a laboratory for research into particle physics. It accelerates protons down a 27km circular tube.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/CERN.jpg",
          city_id: 12,
        },
        {
          name: "Palais des Nations",
          description: "After New York, Geneva has the second most important United Nations office. The Palais des Nations dates to the 1930s and was the headquarters for the League of Nations, the UN’s predecessor.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Palais-des-Nations.jpg",
          city_id: 12,
        },
        {
          name: "Conservatoire et Jardin Botaniques",
          description: "Geneva's premier botanical park – renowned for its Botanical Conservatory – boasts over 12,000 species of plants from around the world, meticulously arranged in a series of beautiful themed gardens.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Conservatory-and-Botanical-Garden.jpg",
          city_id: 12,
        },
        {
          name: "Fraumünster",
          description: "This 13th-century church is renowned for its stunning stained-glass windows, designed by the Russian-Jewish master Marc Chagall. The rose window in the northern transept was created by Augusto Giacometti in 1945.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Fraum%C3%BCnster.jpg",
          city_id: 13,
        },
        {
          name: "Grossmünster",
          description: "The two towers of this Romanesque church could well be Zürich’s most prominent landmark. The Grossmünster, originally a monastic church, was begun at the start of the 12th century and was finished just over a century later.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Grossm%C3%BCnster.jpg",
          city_id: 13,
        },
        {
          name: "Museum of Fine Arts",
          description: "Zürich’s impressive fine-arts gallery boasts a rich collection of largely European art. It stretches from the Middle Ages through a mix of Old Masters to Alberto Giacometti stick figures, Monet and van Gogh masterpieces",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Museum-of-Art.jpg",
          city_id: 13,
        },
        {
          name: "Niederdorf",
          description: "On the Limmat River’s east bank, the winding cobbled streets of Niederdorf are crammed with restaurants, bars, galleries, bookshops and craft shops. Affectionately dubbed 'Dörfli' by locals, the quarter has a laid-back vibe.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Niederdorf.jpg",
          city_id: 13,
        },
        {
          name: "Lindenhof",
          description: "Spectacular views across the Limmat to the Grossmünster can be enjoyed from a tree-shaded hilltop park, smack in the heart of the Old Town.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/Lindenhof.jpg",
          city_id: 13,
        },
        {
          name: "St Peterskirche",
          description: "From any position in the city, it’s hard to overlook the 13th-century tower of this church. Its prominent clock face, 8.7m in diameter, is the largest in Europe.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/08/St-Peter.jpg",
          city_id: 13,
        },
        {
          name: "Cathédrale Notre-Dame",
          description: "Nothing prepares you for your first glimpse of Strasbourg's Cathédrale Notre-Dame, completed in all its Gothic grandeur in 1439. The lace-fine facade lifts the gaze little by little to flying buttresses, leering gargoyles and a 142m spire.",
          activity_image: "https://i.pinimg.com/originals/94/d3/57/94d3577702d347ed4ee567d8701e6e28.jpg",
          city_id: 14,
        },
        {
          name: "Petite France",
          description: "Criss-crossed by narrow lanes, canals and locks, Petite France is where artisans plied their trades in the Middle Ages. The half-timbered houses, sprouting veritable thickets of scarlet geraniums in summer, and the riverside parks attract the masses.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Rue-du-Bain-aux-Plantes-.jpg",
          city_id: 14,
        },
        {
          name: "Palais des Rohan",
          description: "Hailed as a ‘Versailles in miniature’, this opulent 18th-century residence is loaded with treasures. The basement Musée Archéologique takes you from the Palaeolithic period to AD 800. On the ground floor is the Musée des Arts Décoratifs",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Palais-des-Rohan.jpg",
          city_id: 14,
        },
        {
          name: "Ponts Couverts",
          description: "Heralding your entry to Petite France is a set of three fortified bridges that you’ll know for their four tall square towers. These were built in the 1300s and were part of the city’s original line of ramparts.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Ponts-Couverts.jpg",
          city_id: 14,
        },
        {
          name: "Parc de l’Orangerie",
          description: "Across from the Council of Europe's Palais de l’Europe, 2km northeast of Grande Île, this flowery park, designed in the 17th century by Le Nôtre, of Versailles fame, is a family magnet with its playgrounds and swan-dotted lake.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Parc-de-lOrangerie.jpg",
          city_id: 14,
        },
        {
          name: "Barrage Vauban",
          description: "A triumph of 17th-century engineering, the Barrage Vauban bears the architectural imprint of the leading French military engineer of the age – Sébastien Le Prestre de Vauban.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/10/Barrage-Vauban.jpg",
          city_id: 14,
        },
        {
          name: "Musée du Louvre",
          description: "It isn’t until you’re standing in the vast courtyard of the Louvre, with sunlight shimmering through the glass pyramid and crowds milling about beneath the museum’s ornate facade, that you can truly say you’ve been to Paris",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/11/ccimage-shutterstock_227545819.jpg",
          city_id: 15,
        },
        {
          name: "Eiffel Tower",
          description: "No one could imagine Paris today without it. But Gustave Eiffel only constructed this elegant, 324m-tall signature spire as a temporary exhibit for the 1889 World's Fair. Luckily, the art nouveau tower’s popularity assured its survival.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/11/ccimage-shutterstock_167523137.jpg",
          city_id: 15,
        },
        {
          name: "Basilique du Sacré-Cœur",
          description: "Begun in 1875 in the wake of the Franco-Prussian War and the chaos of the Paris Commune, Sacré-Cœur is a symbol of the former struggle between the conservative Catholic old guard and the secular, republican radicals.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/7ad4233f75ec81e3a9a38897ee57353d-basilique-du-sacre-coeur.jpg?fit=crop&w=1920&h=832",
          city_id: 15,
        },
        {
          name: "Musée d’Orsay",
          description: "The home of France’s national collection from the impressionist, post-impressionist and art nouveau movements spanning from 1848 to 1914 is the glorious former Gare d’Orsay train station – itself an art nouveau showpiece",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/11/ccimage-shutterstock_234528289.jpg",
          city_id: 15,
        },
        {
          name: "Cathédrale Notre Dame de Paris",
          description: "While its interior is closed off to visitors following the devastating fire of April 2019, this masterpiece of French Gothic architecture remains the city’s geographic and spiritual heart.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/7ac15ee1af8db7cba9af61e1491f8daf-cathedrale-notre-dame-de-paris.jpg?fit=crop&w=1920&h=832",
          city_id: 15,
        },
        {
          name: "Arc de Triomphe",
          description: "If anything rivals the Eiffel Tower as the symbol of Paris, it’s this magnificent 1836 monument to Napoléon’s victory at Austerlitz (1805), which he commissioned the following year.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/11/ccimage-shutterstock_214344625.jpg",
          city_id: 15,
        },
        {
          name: "Grand Place",
          description: "Brussels’ magnificent Grand Place is one of the world’s most unforgettable urban ensembles. Oddly hidden, the enclosed cobblestone square is only revealed as you enter on foot from one of six narrow side alleys",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Grand-Place-Brussels.jpg",
          city_id: 16,
        },
        {
          name: "Old England Building",
          description: "This 1899 former department store is an art nouveau showpiece with a black facade aswirl with wrought iron and arched windows. The building contains the groundbreaking MIM music museum, a celebration of music in all its forms.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Old-England-Building-Brussels.jpg",
          city_id: 16,
        },
        {
          name: "Parc du Cinquantenaire",
          description: "Parc du Cinquantenaire was built during Léopold II's reign. It's best known for its cluster of museums – art, history, military and motor vehicles – which house an incredible 350,000 artefacts",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Parc-Du-Cinquantenaire.jpg",
          city_id: 16,
        },
        {
          name: "Manneken-Pis",
          description: "This odd statue has risen to fame and is a popular tourist attraction in the city. The name simply translates to “little man pee” and it has been given this name for obvious reasons. ",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Manneken-Pis-Brussels.jpg",
          city_id: 16,
        },
        {
          name: "Musées Royaux des Beaux-Arts",
          description: "This prestigious museum incorporates the Musée d’Art Ancien (ancient art); the Musée d’Art Moderne (modern art), with works by surrealist Paul Delvaux and fauvist Rik Wouters; and the purpose-built Musée Magritte",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Musee-Royaux-Des-Beaux-Arts.jpg",
          city_id: 16,
        },
        {
          name: "Atomium",
          description: "The space-age Atomium looms 102m over north Brussels’ suburbia, resembling a steel alien from a '60s Hollywood movie. It consists of nine house-sized metallic balls linked by steel tube-columns containing escalators and lifts",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Atomium-Brussels.jpg",
          city_id: 16,
        },
        {
          name: "Museum Plantin-Moretus",
          description: "The medieval building and 1622 courtyard garden alone would be worth a visit, but it's the world's oldest printing press, priceless manuscripts and original type sets that justify this museum's Unesco World Heritage status.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Museum-Plantin-Moretus-Antwerp.jpg",
          city_id: 17,
        },
        {
          name: "Rubenshuis",
          description: "This delightfully indulgent 1611 mansion was built as a home and studio for celebrated painter Pieter Paul Rubens. It was rescued from ruins in 1937 and has been very sensitively restored with furniture that dates from Rubens’ era",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Rubenshuis-Antwerp.jpg",
          city_id: 17,
        },
        {
          name: "Onze-Lieve-Vrouwekathedraal",
          description: "Belgium’s finest Gothic cathedral was 169 years in the making (1352–1521). Wherever you wander in Antwerp, its gracious, 123m-high spire has a habit of popping unexpectedly into view and it rarely fails to prompt a gasp of awe.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/Cathedral-of-Our-Lady-Antwerp.jpg",
          city_id: 17,
        },
        {
          name: "Het Steen",
          description: "On a riverside knoll, Het Steen is a dinky but photogenic castle dating from 1200 and occupying the site of Antwerp’s original Gallo-Roman settlement. While still visible, the site is fenced off until restoration is completed",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/6c28896aaece1cd58cb2b0f5a2517af8-het-steen.jpg?fit=crop&w=1920&h=832",
          city_id: 17,
        },
        {
          name: "MAS Museum",
          description: "Opened in 2011, MAS is a 10-storey complex that redefines the idea of a museum-gallery. Floors are designed around big-idea themes using a barrage of media, from old master paintings and tribal artefacts to video installations",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2016/04/MAS-Museum-Antwerp.jpg",
          city_id: 17,
        },
        {
          name: "Grote Markt",
          description: "As is the case with every great Flemish city, Antwerp’s medieval heart is a classic Grote Markt (market square). Here the triangular, pedestrianised space features the voluptuous, baroque Brabo Fountain",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/c8917526675dab107ba2874f065f3b87-grote-markt.jpg?fit=crop&w=1920&h=832",
          city_id: 17,
        },
        {
          name: "Vondelpark",
          description: "A private park for the wealthy until 1953, Vondelpark now occupies a special place in Amsterdam's heart. It's a magical escape, but also supplies a busy social scene, encompassing cycle ways, pristine lawns and quaint cafes",
          activity_image: "https://www.iamsterdam.com/media/nature-and-parks/visitors-vondelpark-cc-bysa-20-fabio-venni-via-flickr.jpg?w=977",
          city_id: 18,
        },
        {
          name: "Rijksmuseum",
          description: "The Rijksmuseum is among the world's finest art museums, packing in works by local heroes Rembrandt, Vermeer and Van Gogh as well as other masterpieces in the 8000 works on display over 1.5km of galleries.",
          activity_image: "https://thingstodoinamsterdam.com/wp-content/uploads/2015/12/11Rijksmuseum-Iamsterdam-sign.jpg",
          city_id: 18,
        },
        {
          name: "Anne Frank Huis",
          description: "The Anne Frank Huis draws around 1¼ million visitors each year. With Anne’s melancholy bedroom and her actual diary – sitting alone in its glass case, filled with sunnily optimistic writing tempered by quiet despair – it’s a powerful experience.",
          activity_image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Amsterdam_%28NL%29%2C_Anne-Frank-Huis_--_2015_--_7185.jpg",
          city_id: 18,
        },
        {
          name: "Van Gogh Museum",
          description: "It's a moving experience to visit this museum, which traces Van Gogh's life and development via the world's largest collection of his work, both familiar paintings and wonderful little-known pieces.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/fd6e0783a09524e5968e1bd0a9041548-van-gogh-museum.jpg?fit=crop&w=1920&h=832",
          city_id: 18,
        },
        {
          name: "Take a canal cruise",
          description: "Created in the 17th century to keep the sea at bay, Amsterdam’s UNESCO protected canal belt is the quintessential picture-postcard vision of Amsterdam",
          activity_image: "https://www.iamsterdam.com/media/locations-ndtrc/activities-excursions/stromma/stromma-cta-100-highlights-cruise-canals-by-day.jpg?w=977",
          city_id: 18,
        },
        {
          name: "Get lost in the arty Jordaan",
          description: "Originally a working class area, the Jordaan’s narrow streets and quaint buildings now make up one of Amsterdam’s most desirable quarters, dotted with independent art galleries and antiques shops",
          activity_image: "https://www.iamsterdam.com/media/neighbourhoods/jordaan-9-straatjes/amsterdam-negen-straatjesmerijn-roubroeks.jpg?w=977",
          city_id: 18,
        },
        {
          name: "Kaiserdom",
          description: "Frankfurt’s red-sandstone cathedral is dominated by a 95m-high Gothic tower, which can be climbed via 328 steps. Construction began in the 13th century.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_465970562.jpg",
          city_id: 19,
        },
        {
          name: "Städel Museum",
          description: "Founded in 1815, this world-renowned art gallery has an outstanding collection of European art from masters including Dürer, Rembrandt, Rubens, Renoir, Picasso and Cézanne",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/9550fab62fa29b997f59e5dd20a0ee65-stadel-museum.jpg?fit=crop&w=1920&h=832",
          city_id: 19,
        },
        {
          name: "Römerberg",
          description: "The Römerberg is Frankfurt’s old central square. Ornately gabled half-timbered buildings, reconstructed after WWII, give an idea of how beautiful the city’s medieval core once was",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_181536278.jpg",
          city_id: 19,
        },
        {
          name: "Main Tower",
          description: "Frankfurt's skyline wouldn't be the same without the Main Tower, one of the tallest and most distinctive high-rises in town. A great place to get a feel for ‘Mainhattan’",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_174601109.jpg",
          city_id: 19,
        },
        {
          name: "PalmenGarten",
          description: "Established in 1871, Frankfurt's botanical PalmenGarten (palm garden) is filled with tropical hothouses, rose gardens, a bamboo grove and rock garden.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_709085965.jpg",
          city_id: 19,
        },
        {
          name: "Senckenberg Museum",
          description: "Life-size dinosaur mock-ups guard the front of Frankfurt’s natural history museum. Inside the early 1900s neo-baroque building, exhibits cover palaeontology, biology and geology.",
          activity_image: "https://lonelyplanetimages.imgix.net/a/g/hi/t/91b1c74b329a11112c6377b48c95f8c4-senckenberg-museum.jpg?fit=crop&w=1920&h=832",
          city_id: 19,
        },
        {
          name: "Kölner Dom",
          description: "Cologne’s geographical and spiritual heart – and its single-biggest tourist draw – is the magnificent Kölner Dom. With its soaring twin spires, this is the Mt Everest of cathedrals, jam-packed with art and treasures.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_517706482.jpg",
          city_id: 20,
        },
        {
          name: "Museum Ludwig",
          description: "A mecca of modern art, Museum Ludwig presents a tantalising mix of works from all major genres. Fans of German expressionism (Beckmann, Dix, Kirchner) will get their fill",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_39249523.jpg",
          city_id: 20,
        },
        {
          name: "Römisch-Germanisches Museum",
          description: "Sculptures and ruins displayed outside the entrance are merely the overture to a full symphony of Roman artefacts found along the Rhine.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_500270767.jpg",
          city_id: 20,
        },
        {
          name: "Cologne’s Old Town",
          description: "the old world atmosphere still shines through on streets and plazas like Heumarkt and Altermarkt, even among the newer concrete constructions from the post-war period.",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_328002392.jpg",
          city_id: 20,
        },
        {
          name: "Groß St. Martin",
          description: "Part of the skyline since the 12th century, Cologne would be the same without the fabulous crossing tower of Groß St. Martin",
          activity_image: "https://cdn.thecrazytourist.com/wp-content/uploads/2017/09/ccimage-shutterstock_99294278.jpg",
          city_id: 20,
        },
        {
          name: "Church of St Gereon",
          description: "The most eccentric looking of Cologne's many Romanesque churches, St Gereon grew from a late-Roman chapel into this massive complex lidded by a 10-sided dome decorated with delicate ribbed vaulting.",
          activity_image: "https://media-cdn.sygictraveldata.com/media/800x600/612664395a40232133447d33247d383538343637363632",
          city_id: 20,
        },
      ]);
    }),
  ]);
};
