
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return Promise.all([
    knex('activity_links').del(),
    knex.raw('ALTER SEQUENCE activity_links_id_seq RESTART WITH 1'),
    knex('activity_links').then(function() {
      // Inserts seed entries
      return knex('activity_links').insert([
        {
          name: "Lonely Planet guide to el Museo del Prado",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/museo-del-prado/a/poi-sig/399599/360770",
          type: "guide",
          activity_id: 1,
        },
        {
          name: "A Day in the Museo del Prado",
          url: "https://outoftownblog.com/a-day-in-the-museo-del-prado-in-madrid-spain/",
          type: "blog",
          activity_id: 1,
        },
        {
          name: "Guide to parque del buen retiro",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/parque-del-buen-retiro/a/poi-sig/399603/360770",
          type: "guide",
          activity_id: 2,
        },
        {
          name: "Parque del buen retiro perfect for the afternoon",
          url: "https://www.mibauldeblogs.com/que-ver-parque-del-retiro-madrid/",
          type: "blog",
          activity_id: 2,
        },
        {
          name: "Lonely Planet guide to Plaza Mayor",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/plaza-mayor/a/poi-sig/399605/360770",
          type: "guide",
          activity_id: 3,
        },
        {
          name: "Plaza Mayor in Madrid,",
          url: "https://www.bellavitatravels.com/blog/plaza-mayor-in-madrid-spain",
          type: "blog",
          activity_id: 3,
        },
        {
          name: "Lonely Planet guide to Centro de Arte Reina Sofía",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/centro-de-arte-reina-sofia/a/poi-sig/399591/360770",
          type: "guide",
          activity_id: 4,
        },
        {
          name: "THE REINA SOFIA MUSEUM",
          url: "https://www.thefunplan.com/en/blog/the-reina-sofia-museum/",
          type: "blog",
          activity_id: 4,
        },
        {
          name: "Lonely Planet guide to Palacio Real",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/palacio-real/a/poi-sig/1094799/360770",
          type: "guide",
          activity_id: 5,
        },
        {
          name: "The Royal Palace of Madrid",
          url: "https://www.citylifemadrid.com/the-royal-palace-of-madrid/",
          type: "blog",
          activity_id: 5,
        },
        {
          name: "Guide to Plaza de Toros",
          url: "https://www.lonelyplanet.com/spain/madrid/attractions/plaza-de-toros/a/poi-sig/1205219/360770",
          type: "guide",
          activity_id: 6,
        },
        {
          name: "A Tour of the Plaza de Toros Las Ventas",
          url: "https://www.citylifemadrid.com/tour-plaza-de-toros-las-ventas-madrid-discount/",
          type: "blog",
          activity_id: 6,
        },
        {
          name: "Guide of la Ciudad de las Artes y las Ciencias",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/ciudad-de-las-artes-y-las-ciencias/a/poi-sig/1288225/1004392",
          type: "guide",
          activity_id: 7,
        },

        {
          name: "Verano en la Ciudad de las Artes y las Ciencias",
          url: "https://blog.singularstays.com/2018/08/13/verano-la-ciudad-las-artes-las-ciencias/",
          type: "blog",
          activity_id: 7,
        },
        {
          name: "Lonely Planet guide to la Catedral de Valencia",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/catedral-de-valencia/a/poi-sig/1208739/1004392",
          type: "guide",
          activity_id: 8,
        },

        {
          name: "CATEDRAL DE VALÈNCIA",
          url: "https://www.visitvalencia.com/en/what-to-do-valencia/valencian-culture/monuments-in-valencia/catedral-valencia-cathedral",
          type: "blog",
          activity_id: 8,
        },
        {
          name: "Go to the Museo Nacional de Cerámica",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/museo-nacional-de-ceramica/a/poi-sig/1208766/1004392",
          type: "guide",
          activity_id: 9,
        },

        {
          name: "Our visit at el Museo Nacional de Cerámica",
          url: "https://www.gotaway.ca/spain/valencia/museo-nacional-de-ceramica/",
          type: "blog",
          activity_id: 9,
        },
        {
          name: "La Lonja guide - lonely planet",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/la-lonja/a/poi-sig/1121344/1004392",
          type: "guide",
          activity_id: 10,
        },

        {
          name: "Valencia Silk Exchange (Lonja de la Seda)",
          url: "https://www.timetravelturtle.com/valencia-silk-exchange-spain/",
          type: "blog",
          activity_id: 10,
        },
        {
          name: "Lonely Planet guide to Museo de Bellas Artes",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/museo-de-bellas-artes/a/poi-sig/424869/1004392",
          type: "guide",
          activity_id: 11,
        },

        {
          name: "Visiting the Museum of Fine Arts in Valencia",
          url: "https://drivespain.com/free-valencia-museum-fine-arts/#/searchcars",
          type: "blog",
          activity_id: 11,
        },
        {
          name: "lonely planet guide to el Mercado Central",
          url: "https://www.lonelyplanet.com/spain/valencia/attractions/mercado-central/a/poi-sig/1208756/1004392",
          type: "guide",
          activity_id: 12,
        },

        {
          name: "The Mercado Central",
          url: "https://valencia.for91days.com/the-mercado-central/",
          type: "blog",
          activity_id: 12,
        },
        {
          name: "Lonely Planet to Museo Guggenheim Bilbao",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/museo-guggenheim-bilbao/a/poi-sig/419033/360739",
          type: "guide",
          activity_id: 13,
        },
        {
          name: "The Guggenheim Museum in Bilbao",
          url: "https://thetravelhack.com/travel/the-guggenheim-museum-in-bilbao/",
          type: "blog",
          activity_id: 13,
        },
        {
          name: "Lonely Planet guide to Casco Viejo",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/casco-viejo/a/poi-sig/419023/360739",
          type: "guide",
          activity_id: 14,
        },
        {
          name: "The Top 10 Things to See & Do in Casco Viejo",
          url: "https://theculturetrip.com/europe/spain/articles/the-top-10-things-to-see-do-in-casco-viejo-bilbao/",
          type: "blog",
          activity_id: 14,
        },
        {
          name: "Lonely Planet guide to Museo de Bellas Artes",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/museo-de-bellas-artes/a/poi-sig/1207342/360739",
          type: "guide",
          activity_id: 15,
        },
        {
          name: "Bellas Artes Bilbao",
          url: "",
          type: "http://www.el-lobo-bobo.com/2016/09/museo-de-bellas-artes-de-bilbao.html",
          activity_id: 15,
        },
        {
          name: "Azkuna Zentroa lonely planets",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/azkuna-zentroa-alhondiga/a/poi-sig/1512614/360739",
          type: "guide",
          activity_id: 16,
        },
        {
          name: "Azkuna Zentroa much more than a cultural center",
          url: "https://www.barcelo.com/guia-turismo/en/bilbao/things-to-do/azkuna-zentroa/",
          type: "blog",
          activity_id: 16,
        },
        {
          name: "Lonely Planet - Museo Marítimo Ría de Bilbao",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/museo-maritimo-ria-de-bilbao/a/poi-sig/1129375/360739",
          type: "guide",
          activity_id: 17,
        },
        {
          name: "Museo Connectado maritimo",
          url: "https://www.itsasmuseum.eus/",
          type: "blog",
          activity_id: 17,
        },
        {
          name: "Funicular de Artxanda - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/bilbao/attractions/funicular-de-artxanda/a/poi-sig/419029/360739",
          type: "guide",
          activity_id: 18,
        },
        {
          name: "Visiting el Funicular de Artxanda, Bilbao",
          url: "https://009adventure.blog/2019/06/19/funicular-de-artxanda-bilbao/",
          type: "blog",
          activity_id: 18,
        },
        {
          name: "Aljaferia - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/aljaferia/a/poi-sig/430060/360742",
          type: "guide",
          activity_id: 19,
        },
        {
          name: "Palacio de la Aljafería in Zaragoza",
          url: "https://limbogen.wixsite.com/libertycrane/single-post/2019/05/30/Palacio-de-la-Aljafer%C3%ADa-in-Zaragoza",
          type: "blog",
          activity_id: 19,
        },
        {
          name: "Lonely planet guide to Museo Goya",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/museo-goya-coleccion-ibercaja/a/poi-sig/430076/360742",
          type: "guide",
          activity_id: 20,
        },
        {
          name: "Visiting el Museo Goya",
          url: "https://museogoya.ibercaja.es/actividades-educativas.php",
          type: "blog",
          activity_id: 20,
        },
        {
          name: "La Seo - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/la-seo/a/poi-sig/430072/360742",
          type: "guide",
          activity_id: 21,
        },
        {
          name: "CATEDRAL DEL SALVADOR O LA SEO",
          url: "http://www.zaragoza.es/ciudad/turismo/en/que-visitar/detalle_Monumento?id=0",
          type: "blog",
          activity_id: 21,
        },
        {
          name: "Lonely Planet - Basílica Zaragoza",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/basilica-de-nuestra-senora-del-pilar/a/poi-sig/430062/360742",
          type: "guide",
          activity_id: 22,
        },
        {
          name: "Top Things To Do And See In Zaragoza",
          url: "https://theculturetrip.com/europe/spain/articles/top-things-to-do-and-see-in-zaragoza/",
          type: "blog",
          activity_id: 22,
        },
        {
          name: "Museo del Teatro - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/museo-del-teatro-de-caesaraugusta/a/poi-sig/430090/360742",
          type: "guide",
          activity_id: 23,
        },
        {
          name: "Top Things To Do And See In Zaragoza",
          url: "https://theculturetrip.com/europe/spain/articles/top-things-to-do-and-see-in-zaragoza/",
          type: "blog",
          activity_id: 23,
        },
        {
          name: "Museo Origami - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/zaragoza/attractions/museo-origami/a/poi-sig/1480020/360742",
          type: "guide",
          activity_id: 24,
        },
        {
          name: "The only Museum of origami in the West",
          url: "http://blog.zaragozaturismo.es/en/2016/07/29/museum-origami-west-zaragoza/",
          type: "blog",
          activity_id: 24,
        },
        {
          name: "La Sagrada Família - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/la-sagrada-familia/a/poi-sig/374867/360761",
          type: "guide",
          activity_id: 25,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 25,
        },
        {
          name: "Park Güell - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/park-guell/a/poi-sig/374905/360761",
          type: "guide",
          activity_id: 26,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 26,
        },
        {
          name: "Lonely Planet - Casa Batlló",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/casa-batllo/a/poi-sig/375147/360761",
          type: "guide",
          activity_id: 27,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 27,
        },
        {
          name: "La Rambla - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/la-rambla/a/poi-sig/1105382/360761",
          type: "guide",
          activity_id: 28,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 28,
        },
        {
          name: "Guide to el Museu Nacional d’Art de Catalunya",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/museu-nacional-d-art-de-catalunya/a/poi-sig/375177/360761",
          type: "guide",
          activity_id: 29,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 29,
        },
        {
          name: "La Pedrera - Lonely Planet",
          url: "https://www.lonelyplanet.com/spain/barcelona/attractions/la-pedrera/a/poi-sig/374869/360761",
          type: "guide",
          activity_id: 30,
        },
        {
          name: "15 Best Things to Do in Barcelona (Spain)",
          url: "https://www.thecrazytourist.com/best-things-barcelona-spain/",
          type: "blog",
          activity_id: 30,
        },
        {
          name: "Basilique St-Sernin - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/basilique-st-sernin/a/poi-sig/1065219/1003054",
          type: "guide",
          activity_id: 31,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 31,
        },
        {
          name: "visiting la Place du Capitole",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/place-du-capitole/a/poi-sig/1065217/1003054",
          type: "",
          activity_id: 32,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 32,
        },
        {
          name: "Lonely Planet - Couvent des Jacobins",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/couvent-des-jacobins/a/poi-sig/1192995/1003054",
          type: "guide",
          activity_id: 33,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 33,
        },
        {
          name: "Visiting la Cité de l’Espace",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/cite-de-l-espace/a/poi-sig/1192993/1003054",
          type: "guide",
          activity_id: 34,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 34,
        },
        {
          name: "Lonely Planet - Musée des Augustins",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/musee-des-augustins/a/poi-sig/1065216/1003054",
          type: "guide",
          activity_id: 35,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 35,
        },
        {
          name: "Visiting the Fondation Bemberg",
          url: "https://www.lonelyplanet.com/france/toulouse/attractions/fondation-bemberg/a/poi-sig/1457533/1003054",
          type: "guide",
          activity_id: 36,
        },
        {
          name: "15 Best Things to Do in Toulouse (France)",
          url: "https://www.thecrazytourist.com/15-best-things-toulouse-france/",
          type: "blog",
          activity_id: 36,
        },
        {
          name: "Vieux Port - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/vieux-port/a/poi-sig/1195435/359286",
          type: "guide",
          activity_id: 37,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 37,
        },
        {
          name: "Visiting la Basilique Notre-Dame de la Garde",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/basilique-notre-dame-de-la-garde/a/poi-sig/399731/359286",
          type: "guide",
          activity_id: 38,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 38,
        },
        {
          name: "Lonely Planet - Le Panier",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/le-panier/a/poi-sig/1195462/359286",
          type: "guide",
          activity_id: 39,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 39,
        },
        {
          name: "Lonely Planet - Musée d’Histoire de Marseille",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/musee-d-histoire-de-marseille/a/poi-sig/399753/359286",
          type: "guide",
          activity_id: 40,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 40,
        },
        {
          name: "Visiting Boulevard Longchamp",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/musee-des-beaux-arts/a/poi-sig/1077018/359286",
          type: "guide",
          activity_id: 41,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 41,
        },
        {
          name: "Musée des Civilisations de l’Europe",
          url: "https://www.lonelyplanet.com/france/marseille/attractions/musee-des-civilisations-de-l-europe-et-de-la-mediterranee/a/poi-sig/1226376/359286",
          type: "guide",
          activity_id: 42,
        },
        {
          name: "15 Best Things to Do in Marseille (France)",
          url: "https://www.thecrazytourist.com/15-best-things-marseille-france/",
          type: "blog",
          activity_id: 42,
        },
        {
          name: "Vieux Nice - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/nice/attractions/vieux-nice/a/poi-sig/1196834/1322981",
          type: "guide",
          activity_id: 43,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 43,
        },
        {
          name: "Promenade des Anglais - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/nice/attractions/promenade-des-anglais/a/poi-sig/1196798/1322981",
          type: "guide",
          activity_id: 44,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 44,
        },
        {
          name: "Visit to the Colline du Château",
          url: "https://www.lonelyplanet.com/france/nice/attractions/colline-du-chateau/a/poi-sig/410076/1322981",
          type: "guide",
          activity_id: 45,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 45,
        },
        {
          name: "Cathédrale St-Nicholas - Lonely Planet  ",
          url: "https://www.lonelyplanet.com/france/nice/attractions/cathedrale-orthodoxe-russe-st-nicolas/a/poi-sig/410074/1322981",
          type: "guide",
          activity_id: 46,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 46,
        },
        {
          name: "Musée Matisse - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/nice/attractions/musee-matisse/a/poi-sig/1196791/1322981",
          type: "guide",
          activity_id: 47,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 47,
        },
        {
          name: "Visiting Cours Saleya Market",
          url: "https://www.lonelyplanet.com/france/nice/attractions/cours-saleya-markets/a/poi-sig/410108/1322981",
          type: "guide",
          activity_id: 48,
        },
        {
          name: "15 Best Things to Do in Nice (France)",
          url: "https://www.thecrazytourist.com/15-best-things-nice-france/",
          type: "blog",
          activity_id: 48,
        },
        {
          name: "Fourvière Basilica - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/basilique-notre-dame-de-fourviere/a/poi-sig/417258/359234",
          type: "guide",
          activity_id: 49,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 49,
        },
        {
          name: "Visit of the St-Jean-Baptiste cathedral",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/cathedrale-st-jean-baptiste/a/poi-sig/417260/359234",
          type: "guide",
          activity_id: 50,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 50,
        },
        {
          name: "Musées Gadagne - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/musees-gadagne/a/poi-sig/1192297/359234",
          type: "guide",
          activity_id: 51,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 51,
        },
        {
          name: "Ancient Theatre of Fourvière - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/theatre-romain/a/poi-sig/1192308/359234",
          type: "guide",
          activity_id: 52,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 52,
        },
        {
          name: "Institut Lumière - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/musee-lumiere/a/poi-sig/417306/359234",
          type: "guide",
          activity_id: 53,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 53,
        },
        {
          name: "Place des Terreaux - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/lyon/attractions/place-des-terreaux/a/poi-sig/417316/359234",
          type: "guide",
          activity_id: 54,
        },
        {
          name: "15 Best Things to Do in Lyon (France)",
          url: "https://www.thecrazytourist.com/15-best-things-lyon-france/",
          type: "blog",
          activity_id: 54,
        },
        {
          name: "Palazzo Reale - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/palazzo-reale/a/poi-sig/424703/359924",
          type: "guide",
          activity_id: 55,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 55,
        },
        {
          name: "Visit the Cathedral of San Giovanni Battista",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/cattedrale-di-san-giovanni-battista/a/poi-sig/424667/359924",
          type: "guide",
          activity_id: 56,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 56,
        },
        {
          name: "Mole Antonelliana - Lonely planet",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/mole-antonelliana/a/poi-sig/424679/359924",
          type: "guide",
          activity_id: 57,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 57,
        },
        {
          name: "Lonely Planet - Basilica di Superga",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/basilica-di-superga/a/poi-sig/424657/359924",
          type: "guide",
          activity_id: 58,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 58,
        },
        {
          name: "Reggia di Venaria Reale - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/reggia-di-venaria-reale/a/poi-sig/1255541/359924",
          type: "guide",
          activity_id: 59,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 59,
        },
        {
          name: "Museo Egizio - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/turin/attractions/museo-egizio/a/poi-sig/424689/359924",
          type: "guide",
          activity_id: 60,
        },
        {
          name: "15 Best Things to Do in Turin (Italy)",
          url: "https://www.thecrazytourist.com/15-best-things-turin-italy/",
          type: "blog",
          activity_id: 60,
        },
        {
          name: "Duomo - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/duomo/a/poi-sig/1137450/359947",
          type: "guide",
          activity_id: 61,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "blog",
          activity_id: 61,
        },
        {
          name: "Castello Sforzesco - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/castello-sforzesco/a/poi-sig/1137618/359947",
          type: "guide",
          activity_id: 62,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "",
          activity_id: 62,
        },
        {
          name: "Visit of Pinacoteca di Brera",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/pinacoteca-di-brera/a/poi-sig/1137628/359947",
          type: "guide",
          activity_id: 63,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "blog",
          activity_id: 63,
        },
        {
          name: "The Last Supper - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/the-last-supper/a/poi-sig/1215052/359947",
          type: "guide",
          activity_id: 64,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "blog",
          activity_id: 64,
        },
        {
          name: "Visiting el Museo Nazionale Leonardo da Vinci",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/museo-nazionale-scienza-e-tecnologia-leonardo-da-vinci/a/poi-sig/405580/359947",
          type: "guide",
          activity_id: 65,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "blog",
          activity_id: 65,
        },
        {
          name: "Basilica di Sant'Ambrogio - Lonely Planet",
          url: "https://www.lonelyplanet.com/italy/milan/attractions/basilica-di-santambrogio/a/poi-sig/1137621/359947",
          type: "guide",
          activity_id: 66,
        },
        {
          name: "17 Best Things to Do in Milan (Italy)",
          url: "https://www.thecrazytourist.com/17-best-things-milan-italy/",
          type: "blog",
          activity_id: 66,
        },
        {
          name: "Jet d’Eau - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/geneva/attractions/jet-deau/a/poi-sig/409726/360817",
          type: "guide",
          activity_id: 67,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 67,
        },
        {
          name: "Cathédrale St-Pierre - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/geneva/attractions/cathedrale-st-pierre/a/poi-sig/1115229/360817",
          type: "guide",
          activity_id: 68,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 68,
        },
        {
          name: "Lonely Planet - Vieille Ville",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "guide",
          activity_id: 69,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 69,
        },
        {
          name: "Visit to the CERN",
          url: "https://www.lonelyplanet.com/switzerland/geneva/attractions/cern/a/poi-sig/409720/360817",
          type: "guide",
          activity_id: 70,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 70,
        },
        {
          name: "Palais des Nations - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/geneva/attractions/palais-des-nations/a/poi-sig/409736/360817",
          type: "guide",
          activity_id: 71,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 71,
        },
        {
          name: "Conservatory and Botanical Garden - lonely planet",
          url: "https://www.lonelyplanet.com/switzerland/geneva/attractions/conservatoire-et-jardin-botaniques/a/poi-sig/1574968/360817",
          type: "guide",
          activity_id: 72,
        },
        {
          name: "25 Best Things to Do in Geneva (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-geneva-switzerland/",
          type: "blog",
          activity_id: 72,
        },
        {
          name: "Fraumünster - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/fraumunster/a/poi-sig/405894/360831",
          type: "guide",
          activity_id: 73,
        },
        {
          name: "25 Best Things to Do in Zürich (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 73,
        },
        {
          name: "Grossmünster - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/grossmunster/a/poi-sig/405896/360831",
          type: "guide",
          activity_id: 74,
        },
        {
          name: "25 Best Things to Do in Zürich (Switzerland)",
          url: "https://thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 74,
        },
        {
          name: "Museum of Fine Arts - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/kunsthaus/a/poi-sig/405908/360831",
          type: "guide",
          activity_id: 75,
        },
        {
          name: "25 Best Things to Do in Zürich (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 75,
        },
        {
          name: "Niederdorf - lonely planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/niederdorf/a/poi-sig/1439801/360831",
          type: "guide",
          activity_id: 76,
        },
        {
          name: "25 Best Things to Do in Zürich (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 76,
        },
        {
          name: "Lindenhof - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/lindenhof/a/poi-sig/1501747/360831",
          type: "guide",
          activity_id: 77,
        },
        {
          name: "25 Best Things to Do in Zürich (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 77,
        },
        {
          name: "St Peterskirche - Lonely Planet",
          url: "https://www.lonelyplanet.com/switzerland/zurich/attractions/st-peterskirche/a/poi-sig/405930/360831",
          type: "guide",
          activity_id: 78,
        },
        {
          name: "St Peter - 25 Best Things to Do in Zürich (Switzerland)",
          url: "https://www.thecrazytourist.com/25-best-things-zurich-switzerland/",
          type: "blog",
          activity_id: 78,
        },
        {
          name: "Cathédrale Notre-Dame - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/cathedrale-notre-dame/a/poi-sig/417553/359225",
          type: "guide",
          activity_id: 79,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 79,
        },
        {
          name: "Petite France - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/petite-france/a/poi-sig/417579/359225",
          type: "guide",
          activity_id: 80,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 80,
        },
        {
          name: "Palais des Rohan - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/palais-rohan/a/poi-sig/417575/359225",
          type: "guide",
          activity_id: 81,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 81,
        },
        {
          name: "Ponts Couverts - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/ponts-couverts/a/poi-sig/1262510/359225",
          type: "guide",
          activity_id: 82,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 82,
        },
        {
          name: "Parc de l’Orangerie - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/parc-de-l-orangerie/a/poi-sig/417577/359225",
          type: "guide",
          activity_id: 83,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 83,
        },
        {
          name: "Barrage Vauban",
          url: "https://www.lonelyplanet.com/france/strasbourg/attractions/barrage-vauban/a/poi-sig/1262509/359225",
          type: "guide",
          activity_id: 84,
        },
        {
          name: "15 Best Things to Do in Strasbourg (France)",
          url: "https://www.thecrazytourist.com/15-best-things-strasbourg-france/",
          type: "blog",
          activity_id: 84,
        },
        {
          name: "Musée du Louvre - Lonely Planet",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "guide",
          activity_id: 85,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 85,
        },
        {
          name: "Eiffel Tower - Lonely Planel",
          url: "https://www.lonelyplanet.com/france/paris/attractions/eiffel-tower/a/poi-sig/372147/359279",
          type: "guide",
          activity_id: 86,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 86,
        },
        {
          name: "Basilique du Sacré-Cœur - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/paris/attractions/basilique-du-sacre-coeur/a/poi-sig/372145/359279",
          type: "guide",
          activity_id: 87,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 87,
        },
        {
          name: "Musée d’Orsay - Lonely planet",
          url: "https://www.lonelyplanet.com/france/paris/attractions/musee-d-orsay/a/poi-sig/372151/359279",
          type: "guide",
          activity_id: 88,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 88,
        },
        {
          name: "Cathédrale Notre Dame de Paris - Lonely Planet",
          url: "https://www.lonelyplanet.com/france/paris/attractions/cathedrale-notre-dame-de-paris/a/poi-sig/372127/359279",
          type: "guide",
          activity_id: 89,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 89,
        },
        {
          name: "Arc de Triomphe - Lonely Planet",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "guide",
          activity_id: 90,
        },
        {
          name: "75 Best Things to Do in Paris (France)",
          url: "https://www.thecrazytourist.com/best-things-see-paris/",
          type: "blog",
          activity_id: 90,
        },
        {
          name: "Grand Place - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/brussels/attractions/grand-place/a/poi-sig/404664/358708",
          type: "guide",
          activity_id: 91,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 91,
        },
        {
          name: "Old England Building - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/brussels/attractions/old-england-building/a/poi-sig/1260878/358708",
          type: "guide",
          activity_id: 92,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 92,
        },
        {
          name: "Parc du Cinquantenaire - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/brussels/attractions/parc-du-cinquantenaire/a/poi-sig/404708/358708",
          type: "guide",
          activity_id: 93,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 93,
        },
        {
          name: "Manneken-Pis guide",
          url: "https://www.brussels.be/manneken-pis",
          type: "guide",
          activity_id: 94,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 94,
        },
        {
          name: "Musées Royaux des Beaux-Arts - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/brussels/attractions/musees-royaux-des-beaux-arts/a/poi-sig/1172813/358708",
          type: "guide",
          activity_id: 95,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 95,
        },
        {
          name: "Atomium - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/brussels/attractions/atomium/a/poi-sig/404662/358708",
          type: "guide",
          activity_id: 96,
        },
        {
          name: "15 Best Things to Do in Brussels (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-brussels-belgium/",
          type: "blog",
          activity_id: 96,
        },
        {
          name: "Museum Plantin-Moretus - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/museum-plantin-moretus/a/poi-sig/425579/358710",
          type: "guide",
          activity_id: 97,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/2/",
          type: "blog",
          activity_id: 97,
        }, 
        {
          name: "Rubenshuis - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/rubenshuis/a/poi-sig/425633/358710",
          type: "guide",
          activity_id: 98,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/2/",
          type: "blog",
          activity_id: 98,
        },
        {
          name: "Onze-Lieve-Vrouwekathedraal - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/onze-lieve-vrouwekathedraal/a/poi-sig/425595/358710",
          type: "guide",
          activity_id: 99,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/2/",
          type: "blog",
          activity_id: 99,
        }, 
        {
          name: "Het Steen",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/het-steen/a/poi-sig/1261250/358710",
          type: "guide",
          activity_id: 100,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/2/",
          type: "blog",
          activity_id: 100,
        },
        {
          name: "MAS Museum - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/mas/a/poi-sig/1261309/358710",
          type: "guide",
          activity_id: 101,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/11/",
          type: "blog",
          activity_id: 101,
        },
        {
          name: "Grote Markt - Lonely Planet",
          url: "https://www.lonelyplanet.com/belgium/antwerp/attractions/grote-markt/a/poi-sig/1523564/358710",
          type: "guide",
          activity_id: 102,
        },
        {
          name: "15 Best Things to Do in Antwerp (Belgium)",
          url: "https://www.thecrazytourist.com/15-best-things-antwerp/11/",
          type: "blog",
          activity_id: 102,
        },   
        {
          name: "Vondelpark - Lonely Planet",
          url: "https://www.lonelyplanet.com/the-netherlands/amsterdam/attractions/vondelpark/a/poi-sig/1096921/360839",
          type: "guide",
          activity_id: 103,
        },
        {
          name: "Best things to do in Amsterdam",
          url: "https://thingstodoinamsterdam.com/",
          type: "blog",
          activity_id: 103,
        }, 
        {
          name: "Rijksmuseum - Lonely Planet",
          url: "https://www.lonelyplanet.com/the-netherlands/amsterdam/attractions/rijksmuseum/a/poi-sig/387159/360839",
          type: "guide",
          activity_id: 104,
        },
        {
          name: "Best things to do in Amsterdam",
          url: "https://thingstodoinamsterdam.com/",
          type: "blog",
          activity_id: 104,
        },
        {
          name: "Anne Frank Huis - Lonely Planet",
          url: "https://www.lonelyplanet.com/the-netherlands/amsterdam/attractions/anne-frank-huis/a/poi-sig/387165/360839",
          type: "guide",
          activity_id: 105,
        },
        {
          name: "Best things to do in Amsterdam",
          url: "https://thingstodoinamsterdam.com/",
          type: "blog",
          activity_id: 105,
        },
        {
          name: "Van Gogh Museum - lonely planet",
          url: "https://www.lonelyplanet.com/the-netherlands/amsterdam/attractions/van-gogh-museum/a/poi-sig/387163/360839  ",
          type: "guide",
          activity_id: 106,
        },
        {
          name: "Best things to do in Amsterdam",
          url: "https://thingstodoinamsterdam.com/",
          type: "blog",
          activity_id: 106,
        },
        {
          name: "Top 20 things to do in Amsterdam",
          url: "https://www.iamsterdam.com/en/see-and-do/things-to-do/top-20-things-to-do-in-amsterdam",
          type: "guide",
          activity_id: 107,
        },
        {
          name: "Canal Cruise Amsterdam",
          url: "https://thingstodoinamsterdam.com/canal-cruise/",
          type: "blog",
          activity_id: 107,
        },
        {
          name: "Top 20 things to do in Amsterdam",
          url: "https://www.iamsterdam.com/en/see-and-do/things-to-do/top-20-things-to-do-in-amsterdam",
          type: "guide",
          activity_id: 108,
        },
        {
          name: "Best things to do in Amsterdam",
          url: "https://thingstodoinamsterdam.com/canal-cruise/",
          type: "blog",
          activity_id: 108,
        }, 
        {
          name: "Kaiserdom - Lonely planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/kaiserdom/a/poi-sig/405316/1003203",
          type: "guide",
          activity_id: 109,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 109,
        },
        {
          name: "Städel Museum - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/stadel-museum/a/poi-sig/405354/1003203",
          type: "guide",
          activity_id: 110,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 110,
        },
        {
          name: "Römerberg - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/romerberg/a/poi-sig/405350/1003203",
          type: "guide",
          activity_id: 111,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 111,
        },
        {
          name: "Main Tower - lonely planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/main-tower/a/poi-sig/405328/1003203",
          type: "guide",
          activity_id: 112,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 112,
        },   
        {
          name: "PalmenGarten - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/palmengarten/a/poi-sig/405344/1003203",
          type: "guide",
          activity_id: 113,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 113,
        },  
        {
          name: "Senckenberg Museum - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/frankfurt-am-main/attractions/senckenberg-museum/a/poi-sig/1140312/1003203",
          type: "guide",
          activity_id: 114,
        },
        {
          name: "25 Best Things to Do in Frankfurt (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-frankfurt-germany/",
          type: "blog",
          activity_id: 114,
        },    
        {
          name: "Kölner Dom - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/cologne/attractions/kolner-dom/a/poi-sig/456311/359392",
          type: "guide",
          activity_id: 115,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 115,
        },   
        {
          name: "Museum Ludwig - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/cologne/attractions/museum-ludwig/a/poi-sig/456319/359392",
          type: "guide",
          activity_id: 116,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 116,
        }, 
        {
          name: "Römisch-Germanisches Museum - Lonely Planet",
          url: "https://www.lonelyplanet.com/germany/cologne/attractions/romisch-germanisches-museum/a/poi-sig/456323/359392",
          type: "guide",
          activity_id: 117,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 117,
        },
        {
          name: "What to do in cologne?",
          url: "https://www.cologne.de/what-to-do/sightseeing/the-old-town.html",
          type: "guide",
          activity_id: 118,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 118,
        }, 
        {
          name: "a view on cities",
          url: "https://www.aviewoncities.com/cologne/grossstmartin.htm",
          type: "guide",
          activity_id: 119,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 119,
        }, 
        {
          name: "Church of St Gereon - Lonely planet",
          url: "https://www.lonelyplanet.com/germany/cologne/attractions/church-of-st-gereon/a/poi-sig/456327/359392",
          type: "guide",
          activity_id: 120,
        },
        {
          name: "25 Best Things to Do in Cologne (Germany)",
          url: "https://www.thecrazytourist.com/25-best-things-cologne-germany/",
          type: "blog",
          activity_id: 120,
        }, 
      ]);
    }),
  ]);
};