
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return Promise.all([
    knex('transports').del(),
    knex.raw('ALTER SEQUENCE transports_id_seq RESTART WITH 1'),
    knex('transports').then(function () {
      // Inserts seed entries
      return knex('transports').insert([
        {
          company_id: 3,
          price: 43,
          duration: 255,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 3,
          price: 43,
          duration: 255,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 3,
          price: 43,
          duration: 255,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 4,
          price: 52,
          duration: 113,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 4,
          price: 62,
          duration: 104,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 4,
          price: 67,
          duration: 105,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 1,
          price: 56,
          duration: 70,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 2,
          price: 76,
          duration: 60,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 2,
        },
        {
          company_id: 2,
          price: 80,
          duration: 75,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 2,
        },


        {
          company_id: 5,
          price: 49,
          duration: 280,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 5,
          price: 49,
          duration: 280,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 5,
          price: 49,
          duration: 280,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 4,
          price: 46,
          duration: 305,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 4,
          price: 52,
          duration: 360,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 4,
          price: 46,
          duration: 311,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 2,
          price: 97,
          duration: 60,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 1,
          price: 85,
          duration: 60,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 3,
        },
        {
          company_id: 1,
          price: 102,
          duration: 65,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 3,
        },


        {
          company_id: 5,
          price: 26,
          duration: 210,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 4,
        },
        {
          company_id: 5,
          price: 26,
          duration: 210,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 4,
        },
        {
          company_id: 5,
          price: 28,
          duration: 210,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 34,
          duration: 100,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 46,
          duration: 81,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 52,
          duration: 85,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 4,
        },


        {
          company_id: 5,
          price: 51,
          duration: 455,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 48,
          duration: 475,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 50,
          duration: 455,
          transport_type_id: 1,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 50,
          duration: 150,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 76,
          duration: 190,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 82,
          duration: 165,
          transport_type_id: 2,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 63,
          duration: 75,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 1,
          price: 75,
          duration: 85,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 5,
        },
        {
          company_id: 2,
          price: 78,
          duration: 75,
          transport_type_id: 3,
          starting_city: 1,
          ending_city: 5,
        },


        {
          company_id: 5,
          price: 32,
          duration: 210,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 4,
        },
        {
          company_id: 5,
          price: 32,
          duration: 240,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 4,
        },
        {
          company_id: 5,
          price: 32,
          duration: 240,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 32,
          duration: 270,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 32,
          duration: 270,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 32,
          duration: 270,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 4,
        },


        {
          company_id: 4,
          price: 79,
          duration: 738,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 2,
        },
        {
          company_id: 4,
          price: 82,
          duration: 745,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 2,
        },
        {
          company_id: 4,
          price: 85,
          duration: 710,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 2,
        },
        {
          company_id: 6,
          price: 139,
          duration: 250,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 2,
        },
        {
          company_id: 6,
          price: 143,
          duration: 254,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 2,
        },
        {
          company_id: 2,
          price: 176,
          duration: 280,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 2,
        },


        {
          company_id: 5,
          price: 75,
          duration:480,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 75,
          duration:480,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 75,
          duration:480,
          transport_type_id: 1,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 61,
          duration: 410,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 61,
          duration: 414,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 61,
          duration: 410,
          transport_type_id: 2,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 60,
          duration: 70,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 55,
          duration: 70,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 74,
          duration: 70,
          transport_type_id: 3,
          starting_city: 3,
          ending_city: 5,
        },


        {
          company_id: 4,
          price: 54,
          duration: 301,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 54,
          duration: 311,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 4,
        },
        {
          company_id: 4,
          price: 54,
          duration: 295,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 4,
        },


        {
          company_id: 5,
          price: 28,
          duration: 255,
          transport_type_id: 1,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 28,
          duration: 240,
          transport_type_id: 1,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 32,
          duration: 255,
          transport_type_id: 1,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 42,
          duration: 190,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 42,
          duration: 195,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 42,
          duration: 199,
          transport_type_id: 2,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 1,
          price: 59,
          duration: 60,
          transport_type_id: 3,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 55,
          duration: 60,
          transport_type_id: 3,
          starting_city: 2,
          ending_city: 5,
        },
        {
          company_id: 6,
          price: 58,
          duration: 70,
          transport_type_id: 3,
          starting_city: 2,
          ending_city: 5,
        },


        {
          company_id: 5,
          price: 25,
          duration: 210,
          transport_type_id: 1,
          starting_city: 4,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 25,
          duration: 210,
          transport_type_id: 1,
          starting_city: 4,
          ending_city: 5,
        },
        {
          company_id: 5,
          price: 26,
          duration: 210,
          transport_type_id: 1,
          starting_city: 4,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 46,
          duration: 111,
          transport_type_id: 2,
          starting_city: 4,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 38,
          duration: 120,
          transport_type_id: 2,
          starting_city: 4,
          ending_city: 5,
        },
        {
          company_id: 4,
          price: 45,
          duration: 120,
          transport_type_id: 2,
          starting_city: 4,
          ending_city: 5,
        },


        {
          company_id: 7,
          price: 23,
          duration: 365,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 6,
        },
        {
          company_id: 7,
          price: 24,
          duration: 345,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 6,
        },
        {
          company_id: 8,
          price: 36,
          duration: 365,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 6,
        },
        {
          company_id: 2,
          price: 173,
          duration: 225,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 6,
        },
        {
          company_id: 2,
          price: 151,
          duration: 225,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 6,
        },
        {
          company_id: 2,
          price: 142,
          duration: 225,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 6,
        },


        {
          company_id: 7,
          price: 26,
          duration: 455,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 8,
          price: 42,
          duration: 485,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 8,
          price: 36,
          duration: 485,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 6,
          price: 84,
          duration: 65,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 6,
          price: 89,
          duration: 65,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 6,
          price: 84,
          duration: 65,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 7,
        },
        {
          company_id: 6,
          price: 82,
          duration: 65,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 7,
        },


        {
          company_id: 7,
          price: 34,
          duration: 690,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 72,
          duration: 690,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 55,
          duration: 690,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 146,
          duration: 653,
          transport_type_id: 2,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 124,
          duration: 653,
          transport_type_id: 2,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 136,
          duration: 735,
          transport_type_id: 2,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 6,
          price: 160,
          duration: 80,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 9,
          price: 166,
          duration: 85,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 8,
        },
        {
          company_id: 6,
          price: 172,
          duration: 80,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 8,
        },


        {
          company_id: 7,
          price: 29,
          duration: 540,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 9,
        },
        {
          company_id: 8,
          price: 72,
          duration: 525,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 9,
        },
        {
          company_id: 8,
          price: 72,
          duration: 525,
          transport_type_id: 1,
          starting_city: 5,
          ending_city: 9,
        },
        {
          company_id: 6,
          price: 183,
          duration: 90,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 9,
        },
        {
          company_id: 10,
          price: 122,
          duration: 90,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 9,
        },
        {
          company_id: 10,
          price: 122,
          duration: 90,
          transport_type_id: 3,
          starting_city: 5,
          ending_city: 9,
        },


        {
          company_id: 7,
          price: 24,
          duration: 295,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 7,
          price: 29,
          duration: 360,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 7,
          price: 31,
          duration: 455,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 11,
          price: 33,
          duration: 218,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 11,
          price: 31,
          duration: 229,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 11,
          price: 33,
          duration: 238,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 12,
          price: 16,
          duration: 60,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 13,
          price: 244,
          duration: 135,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 13,
          price: 238,
          duration: 125,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },


        {
          company_id: 7,
          price: 17,
          duration: 485,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 37,
          duration: 575,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 44,
          duration: 565,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 32,
          duration: 466,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 56,
          duration: 547,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 41,
          duration: 457,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 9,
          price: 83,
          duration: 70,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 9,
          price: 94,
          duration: 70,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 8,
        },
        {
          company_id: 9,
          price: 118,
          duration: 75,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 8,
        },


        {
          company_id: 7,
          price: 29,
          duration: 515,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 8,
          price: 38,
          duration: 510,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 7,
          price: 32,
          duration: 515,
          transport_type_id: 1,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 70,
          duration: 336,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 72,
          duration: 362,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 82,
          duration: 307,
          transport_type_id: 2,
          starting_city: 6,
          ending_city: 9,
        },
        {
          company_id: 9,
          price: 141,
          duration: 60,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 9,
          price: 172,
          duration: 70,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },
        {
          company_id: 9,
          price: 202,
          duration: 65,
          transport_type_id: 3,
          starting_city: 6,
          ending_city: 7,
        },


        {
          company_id: 7,
          price: 8,
          duration: 165,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 12,
          duration: 200,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 8,
        },
        {
          company_id: 8,
          price: 17,
          duration: 190,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 38,
          duration: 160,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 38,
          duration: 160,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 38,
          duration: 160,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 8,
        },


        {
          company_id: 7,
          price: 14,
          duration: 250,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 7,
          price: 14,
          duration: 250,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 7,
          price: 14,
          duration: 250,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 45,
          duration: 107,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 48,
          duration: 106,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 11,
          price: 45,
          duration: 110,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 13,
          price: 302,
          duration: 55,
          transport_type_id: 3,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 13,
          price: 256,
          duration: 55,
          transport_type_id: 3,
          starting_city: 7,
          ending_city: 9,
        },
        {
          company_id: 13,
          price: 262,
          duration: 55,
          transport_type_id: 3,
          starting_city: 7,
          ending_city: 9,
        },


        {
          company_id: 14,
          price: 28,
          duration: 650,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 10,
        },
        {
          company_id: 14,
          price: 56,
          duration: 610,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 10,
        },
        {
          company_id: 14,
          price: 29,
          duration: 710,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 10,
        },
        {
          company_id: 15,
          price: 57,
          duration: 480,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 10,
        },
        {
          company_id: 15,
          price: 61,
          duration: 492,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 10,
        },
        {
          company_id: 15,
          price: 52,
          duration: 490,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 10,
        },


        {
          company_id: 7,
          price: 19,
          duration: 560,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 12,
        },
        {
          company_id: 7,
          price: 22,
          duration: 560,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 12,
        },
        {
          company_id: 7,
          price: 21,
          duration: 560,
          transport_type_id: 1,
          starting_city: 7,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 81,
          duration: 231,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 85,
          duration: 230,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 86,
          duration: 210,
          transport_type_id: 2,
          starting_city: 7,
          ending_city: 12,
        },


        {
          company_id: 7,
          price: 28,
          duration: 455,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 28,
          duration: 450,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 28,
          duration: 450,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 64,
          duration: 285,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 87,
          duration: 282,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 11,
          price: 92,
          duration: 328,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 13,
          price: 310,
          duration: 55,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 13,
          price: 317,
          duration: 55,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 8,
        },
        {
          company_id: 13,
          price: 327,
          duration: 60,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 8,
        },


        {
          company_id: 7,
          price: 300,
          duration: 23,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 10,
        },
        {
          company_id: 7,
          price: 346,
          duration: 29,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 10,
        },
        {
          company_id: 7,
          price: 330,
          duration: 27,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 10,
        },
        {
          company_id: 11,
          price: 72,
          duration: 222,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 10,
        },
        {
          company_id: 11,
          price: 74,
          duration: 220,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 10,
        },
        {
          company_id: 11,
          price: 69,
          duration: 205,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 10,
        },
        

        {
          company_id: 7,
          price: 15,
          duration: 150,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 12,
        },
        {
          company_id: 7,
          price: 11,
          duration: 180,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 12,
        },
        {
          company_id: 8,
          price: 19,
          duration: 150,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 45,
          duration: 111,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 45,
          duration: 111,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 12,
        },
        {
          company_id: 11,
          price: 45,
          duration: 140,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 12,
        },


        {
          company_id: 7,
          price: 23,
          duration: 420,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 23,
          duration: 305,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 23,
          duration: 305,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 11,
          price: 69,
          duration: 123,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 11,
          price: 84,
          duration: 117,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 11,
          price: 72,
          duration: 120,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 13,
          price: 174,
          duration: 70,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 13,
          price: 174,
          duration: 70,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 15,
        },
        {
          company_id: 13,
          price: 174,
          duration: 70,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 15,
        },


        {
          company_id: 7,
          price: 38,
          duration: 415,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 7,
          price: 42,
          duration: 420,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 8,
          price: 39,
          duration: 425,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 11,
          price: 70,
          duration: 237,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 11,
          price: 75,
          duration: 227,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 11,
          price: 84,
          duration: 209,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 13,
          price: 288,
          duration: 65,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 13,
          price: 305,
          duration: 65,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 14,
        },
        {
          company_id: 13,
          price: 230,
          duration: 60,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 14,
        },


        {
          company_id: 16,
          price: 72,
          duration: 745,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 16,
          price: 65,
          duration: 735,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 16,
          price: 63,
          duration: 710,
          transport_type_id: 1,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 11,
          price: 82,
          duration: 318,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 11,
          price: 88,
          duration: 329,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 11,
          price: 82,
          duration: 350,
          transport_type_id: 2,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 10,
          price: 137,
          duration: 275,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 13,
          price: 154,
          duration: 210,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 13,
        },
        {
          company_id: 13,
          price: 154,
          duration: 200,
          transport_type_id: 3,
          starting_city: 9,
          ending_city: 13,
        },


        {
          company_id: 5,
          price: 28,
          duration: 595,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 8,
        },
        {
          company_id: 5,
          price: 27,
          duration: 610,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 8,
        },
        {
          company_id: 7,
          price: 25,
          duration: 735,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 8,
        },
        {
          company_id: 15,
          price: 33,
          duration: 335,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 8,
        },
        {
          company_id: 15,
          price: 49,
          duration: 334,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 8,
        },
        {
          company_id: 15,
          price: 52,
          duration: 329,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 8,
        },


        {
          company_id: 17,
          price: 12,
          duration: 125,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 11,
        },
        {
          company_id: 17,
          price: 14,
          duration: 120,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 11,
        },
        {
          company_id: 17,
          price: 11,
          duration: 105,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 11,
        },
        {
          company_id: 18,
          price: 16,
          duration: 57,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 11,
        },
        {
          company_id: 18,
          price: 16,
          duration: 60,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 11,
        },
        {
          company_id: 18,
          price: 18,
          duration: 55,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 11,
        },


        {
          company_id: 14,
          price: 25,
          duration: 260,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 12,
        },
        {
          company_id: 14,
          price: 29,
          duration: 225,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 12,
        },
        {
          company_id: 14,
          price: 25,
          duration: 260,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 12,
        },
        {
          company_id: 15,
          price: 79,
          duration: 390,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 12,
        },
        {
          company_id: 15,
          price: 84,
          duration: 334,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 12,
        },
        {
          company_id: 15,
          price: 96,
          duration: 348,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 12,
        },


        {
          company_id: 17,
          price: 45,
          duration: 380,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 13,
        },
        {
          company_id: 17,
          price: 42,
          duration: 380,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 13,
        },
        {
          company_id: 17,
          price: 48,
          duration: 380,
          transport_type_id: 1,
          starting_city: 10,
          ending_city: 13,
        },
        {
          company_id: 15,
          price: 63,
          duration: 356,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 13,
        },
        {
          company_id: 15,
          price: 63,
          duration: 356,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 13,
        },
        {
          company_id: 15,
          price: 63,
          duration: 356,
          transport_type_id: 2,
          starting_city: 10,
          ending_city: 13,
        },


        {
          company_id: 14,
          price: 32,
          duration: 315,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 14,
          price: 32,
          duration: 315,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 14,
          price: 32,
          duration: 310,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 19,
          price: 72,
          duration: 161,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 19,
          price: 37,
          duration: 176,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 19,
          price: 43,
          duration: 182,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 20,
          price: 196,
          duration: 50,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 20,
          price: 196,
          duration: 55,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 13,
        },
        {
          company_id: 20,
          price: 196,
          duration: 45,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 13,
        },


        {
          company_id: 7,
          price: 23,
          duration: 320,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 7,
          price: 23,
          duration: 320,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 7,
          price: 23,
          duration: 320,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 60,
          duration: 238,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 60,
          duration: 238,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 75,
          duration: 238,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 13,
          price: 144,
          duration: 215,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 13,
          price: 144,
          duration: 275,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 11,
        },
        {
          company_id: 13,
          price: 144,
          duration: 265,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 11,
        },


        {
          company_id: 14,
          price: 35,
          duration: 475,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 14,
        },
        {
          company_id: 14,
          price: 35,
          duration: 475,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 14,
        },
        {
          company_id: 14,
          price: 35,
          duration: 635,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 14,
        },
        {
          company_id: 21,
          price: 70,
          duration: 357,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 14,
        },
        {
          company_id: 21,
          price: 76,
          duration: 351,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 14,
        },
        {
          company_id: 21,
          price: 70,
          duration: 346,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 14,
        },
        

        {
          company_id: 7,
          price: 29,
          duration: 500,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 29,
          duration: 500,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 34,
          duration: 655,
          transport_type_id: 1,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 75,
          duration: 188,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 75,
          duration: 188,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 67,
          duration: 188,
          transport_type_id: 2,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 9,
          price: 52,
          duration: 65,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 9,
          price: 77,
          duration: 70,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 15,
        },
        {
          company_id: 9,
          price: 79,
          duration: 65,
          transport_type_id: 3,
          starting_city: 12,
          ending_city: 15,
        },


        {
          company_id: 16,
          price: 31,
          duration: 330,
          transport_type_id: 1,
          starting_city: 8,
          ending_city: 11,
        },
        {
          company_id: 16,
          price: 31,
          duration: 330,
          transport_type_id: 1,
          starting_city: 8,
          ending_city: 11,
        },
        {
          company_id: 16,
          price: 31,
          duration: 330,
          transport_type_id: 1,
          starting_city: 8,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 43,
          duration: 292,
          transport_type_id: 2,
          starting_city: 8,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 43,
          duration: 292,
          transport_type_id: 2,
          starting_city: 8,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 43,
          duration: 285,
          transport_type_id: 2,
          starting_city: 8,
          ending_city: 11,
        },


        {
          company_id: 8,
          price: 38,
          duration: 265,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 8,
          price: 42,
          duration: 265,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 8,
          price: 42,
          duration: 285,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 45,
          duration: 220,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 45,
          duration: 220,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 15,
          price: 45,
          duration: 220,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 10,
          price: 122,
          duration: 210,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 10,
          price: 125,
          duration: 215,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 11,
        },
        {
          company_id: 13,
          price: 145,
          duration: 250,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 11,
        },


        {
          company_id: 17,
          price: 43,
          duration: 435,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 17,
          price: 42,
          duration: 435,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 17,
          price: 45,
          duration: 435,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 46,
          duration: 232,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 46,
          duration: 232,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 40,
          duration: 232,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 13,
          price: 165,
          duration: 235,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 13,
          price: 165,
          duration: 235,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 223,
          duration: 275,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 19,
        },


        {
          company_id: 14,
          price: 16,
          duration: 220,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 14,
        },
        {
          company_id: 14,
          price: 16,
          duration: 260,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 14,
        },
        {
          company_id: 14,
          price: 16,
          duration: 245,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 14,
        },


        {
          company_id: 14,
          price: 40,
          duration: 525,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 14,
          price: 46,
          duration: 585,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 14,
          price: 45,
          duration: 600,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 305,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 40,
          duration: 357,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 40,
          duration: 357,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 76,
          duration: 70,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 107,
          duration: 70,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 122,
          duration: 70,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 20,
        },


        {
          company_id: 7,
          price: 64,
          duration: 1095,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 72,
          duration: 1080,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 7,
          price: 76,
          duration: 1115,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 75,
          duration: 243,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 75,
          duration: 243,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 22,
          price: 93,
          duration: 244,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 20,
          price: 123,
          duration: 80,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 20,
          price: 123,
          duration: 75,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 15,
        },
        {
          company_id: 10,
          price: 107,
          duration: 90,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 15,
        },


        {
          company_id: 14,
          price: 43,
          duration: 645,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 14,
          price: 61,
          duration: 645,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 14,
          price: 60,
          duration: 645,
          transport_type_id: 1,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 21,
          price: 84,
          duration: 506,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 21,
          price: 84,
          duration: 506,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 21,
          price: 84,
          duration: 514,
          transport_type_id: 2,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 205,
          duration: 200,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 205,
          duration: 300,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 16,
        },
        {
          company_id: 24,
          price: 188,
          duration: 390,
          transport_type_id: 3,
          starting_city: 13,
          ending_city: 16,
        },


        {
          company_id: 7,
          price: 18,
          duration: 195,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 16,
          duration: 238,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 34,
          duration: 226,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 19,
        },
        {
          company_id: 11,
          price: 46,
          duration: 107,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 46,
          duration: 105,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 46,
          duration: 126,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 19,
        },



        {
          company_id: 8,
          price: 37,
          duration: 925,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 35,
          duration: 910,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 33,
          duration: 930,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 54,
          duration: 234,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 20,
        },
        {
          company_id: 25,
          price: 60,
          duration: 224,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 20,
        },
        {
          company_id: 25,
          price: 60,
          duration: 225,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 20,
        },


        {
          company_id: 7,
          price: 20,
          duration: 395,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 7,
          price: 20,
          duration: 395,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 8,
          price: 29,
          duration: 425,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 26,
          price: 168,
          duration: 216,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 26,
          price: 155,
          duration: 274,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 11,
          price: 178,
          duration: 275,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 13,
          price: 307,
          duration: 205,
          transport_type_id: 3,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 311,
          duration: 245,
          transport_type_id: 3,
          starting_city: 14,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 316,
          duration: 245,
          transport_type_id: 3,
          starting_city: 14,
          ending_city: 16,
        },


        {
          company_id: 8,
          price: 29,
          duration: 525,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 17,
        },
        {
          company_id: 8,
          price: 30,
          duration: 525,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 17,
        },
        {
          company_id: 8,
          price: 32,
          duration: 525,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 17,
        },


        {
          company_id: 7,
          price: 14,
          duration: 420,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 15,
        },
        {
          company_id: 8,
          price: 22,
          duration: 362,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 15,
        },
        {
          company_id: 8,
          price: 22,
          duration: 376,
          transport_type_id: 1,
          starting_city: 14,
          ending_city: 15,
        },
        {
          company_id: 26,
          price: 104,
          duration: 115,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 15,
        },
        {
          company_id: 26,
          price: 104,
          duration: 108,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 15,
        },
        {
          company_id: 26,
          price: 104,
          duration: 109,
          transport_type_id: 2,
          starting_city: 14,
          ending_city: 15,
        },
        


        {
          company_id: 7,
          price: 16,
          duration: 230,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 7,
          price: 16,
          duration: 230,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 8,
          price: 19,
          duration: 225,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 27,
          price: 99,
          duration: 82,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 27,
          price: 99,
          duration: 83,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 27,
          price: 99,
          duration: 82,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 244,
          duration: 230,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 256,
          duration: 230,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 16,
        },
        {
          company_id: 23,
          price: 234,
          duration: 230,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 16,
        },


        {
          company_id: 7,
          price: 20,
          duration: 294,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 17,
        },
        {
          company_id: 7,
          price: 17,
          duration: 524,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 17,
        },
        {
          company_id: 8,
          price: 20,
          duration: 530,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 17,
        },
        {
          company_id: 27,
          price: 86,
          duration: 122,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 17,
        },
        {
          company_id: 27,
          price: 86,
          duration: 122,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 17,
        },
        {
          company_id: 27,
          price: 111,
          duration: 149,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 17,
        },


        {
          company_id: 8,
          price: 23,
          duration: 420,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 8,
          price: 23,
          duration: 390,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 8,
          price: 23,
          duration: 510,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 27,
          price: 148,
          duration: 199,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 27,
          price: 148,
          duration: 199,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 27,
          price: 148,
          duration: 199,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 28,
          price: 75,
          duration: 75,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 28,
          price: 70,
          duration: 90,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 18,
        },
        {
          company_id: 24,
          price: 155,
          duration: 75,
          transport_type_id: 3,
          starting_city: 15,
          ending_city: 18,
        },


        {
          company_id: 8,
          price: 26,
          duration: 444,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 32,
          duration: 424,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 28,
          duration: 440,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 20,
        },
        {
          company_id: 27,
          price: 92,
          duration: 215,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 69,
          duration: 345,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 69,
          duration: 345,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 20,
        },


        {
          company_id: 7,
          price: 29,
          duration: 530,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 29,
          duration: 530,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 29,
          duration: 560,
          transport_type_id: 1,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 11,
          price: 61,
          duration: 218,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 11,
          price: 61,
          duration: 228,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 11,
          price: 60,
          duration: 228,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 29,
          price: 190,
          duration: 75,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 29,
          price: 190,
          duration: 75,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },
        {
          company_id: 29,
          price: 190,
          duration: 75,
          transport_type_id: 2,
          starting_city: 15,
          ending_city: 19,
        },


        {
          company_id: 14,
          price: 7,
          duration: 50,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 17,
        },
        {
          company_id: 14,
          price: 7,
          duration: 60,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 17,
        },
        {
          company_id: 14,
          price: 7,
          duration: 65,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 17,
        },
        {
          company_id: 30,
          price: 15,
          duration: 46,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 17,
        },
        {
          company_id: 30,
          price: 15,
          duration: 46,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 17,
        },
        {
          company_id: 30,
          price: 15,
          duration: 46,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 17,
        },


        {
          company_id: 8,
          price: 14,
          duration: 210,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 7,
          price: 16,
          duration: 180,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 8,
          price: 14,
          duration: 150,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 30,
          price: 40,
          duration: 174,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 30,
          price: 45,
          duration: 173,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 27,
          price: 125,
          duration: 112,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 10,
          price: 137,
          duration: 360,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 23,
          price: 256,
          duration: 55,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 18,
        },
        {
          company_id: 23,
          price: 288,
          duration: 55,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 18,
        },

        {
          company_id: 7,
          price: 22,
          duration: 355,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 22,
          duration: 385,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 22,
          duration: 370,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 92,
          duration: 186,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 92,
          duration: 186,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 91,
          duration: 177,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 223,
          duration: 180,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 226,
          duration: 240,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 226,
          duration: 260,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 19,
        },


        {
          company_id: 7,
          price: 11,
          duration: 180,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 14,
          duration: 175,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 8,
          price: 14,
          duration: 175,
          transport_type_id: 1,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 110,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 38,
          duration: 110,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 112,
          transport_type_id: 2,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 20,
          price: 563,
          duration: 190,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 20,
          price: 563,
          duration: 190,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 20,
        },
        {
          company_id: 20,
          price: 563,
          duration: 190,
          transport_type_id: 3,
          starting_city: 16,
          ending_city: 20,
        },
        

        {
          company_id: 8,
          price: 14,
          duration: 150,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 18,
        },
        {
          company_id: 8,
          price: 16,
          duration: 165,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 18,
        },
        {
          company_id: 8,
          price: 17,
          duration: 165,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 18,
        },
        {
          company_id: 27,
          price: 45,
          duration: 74,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 18,
        },
        {
          company_id: 30,
          price: 32,
          duration: 111,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 18,
        },
        {
          company_id: 30,
          price: 35,
          duration: 111,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 18,
        },


        {
          company_id: 21,
          price: 107,
          duration: 313,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 107,
          duration: 313,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 107,
          duration: 305,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 107,
          duration: 216,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 107,
          duration: 207,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 107,
          duration: 216,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 19,
        },


        {
          company_id: 8,
          price: 22,
          duration: 400,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 31,
          duration: 253,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 32,
          duration: 242,
          transport_type_id: 1,
          starting_city: 17,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 38,
          duration: 140,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 157,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 38,
          duration: 170,
          transport_type_id: 2,
          starting_city: 17,
          ending_city: 20,
        },


        {
          company_id: 7,
          price: 31,
          duration: 385,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 31,
          duration: 455,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 7,
          price: 31,
          duration: 415,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 61,
          duration: 313,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 69,
          duration: 278,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 21,
          price: 70,
          duration: 387,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 240,
          duration: 70,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 232,
          duration: 75,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 19,
        },
        {
          company_id: 23,
          price: 236,
          duration: 65,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 19,
        },


        {
          company_id: 7,
          price: 20,
          duration: 245,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 7,
          price: 20,
          duration: 300,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 7,
          price: 20,
          duration: 325,
          transport_type_id: 1,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 31,
          duration: 158,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 38,
          duration: 157,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 154,
          transport_type_id: 2,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 137,
          duration: 175,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 137,
          duration: 175,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 20,
        },
        {
          company_id: 10,
          price: 137,
          duration: 175,
          transport_type_id: 3,
          starting_city: 18,
          ending_city: 20,
        },


        {
          company_id: 7,
          price: 11,
          duration: 125,
          transport_type_id: 1,
          starting_city: 19,
          ending_city: 20,
        },
        {
          company_id: 7,
          price: 11,
          duration: 125,
          transport_type_id: 1,
          starting_city: 19,
          ending_city: 20,
        },
        {
          company_id: 7,
          price: 11,
          duration: 125,
          transport_type_id: 1,
          starting_city: 19,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 31,
          duration: 63,
          transport_type_id:  2,
          starting_city: 19,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 40,
          duration: 64,
          transport_type_id:  2,
          starting_city: 19,
          ending_city: 20,
        },
        {
          company_id: 21,
          price: 46,
          duration: 65,
          transport_type_id:  2,
          starting_city: 19,
          ending_city: 20,
        },
      ]);
    }),
  ]);
};
